# Generated by Django 4.2.7 on 2025-10-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0003_checkdetail_receiptiddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='check_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='ekispiditor',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='project',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='sklad',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('delivered', 'Yetkazilgan'), ('failed', 'Muvaffaqiyatsiz'), ('pending', 'Kutilmoqda')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='check',
            name='yetkazilgan_vaqti',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkdetail',
            name='check_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkdetail',
            name='check_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='checkdetail',
            name='total_sum',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ProblemCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(db_index=True, max_length=100)),
                ('issue_code', models.CharField(db_index=True, max_length=50)),
                ('issue_message', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name_plural': 'Problem Checks',
                'indexes': [models.Index(fields=['issue_code', 'resolved'], name='expeditor_a_issue_c_0d3630_idx'), models.Index(fields=['detected_at'], name='expeditor_a_detecte_c02d9f_idx')],
            },
        ),
    ]
