# Generated by Django 4.2.7 on 2025-10-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0008_emailconfig_tasklist_alter_emailrecipient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120, null=True)),
                ('username', models.CharField(blank=True, help_text='Telegram @username without @', max_length=120, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='International format like +99890...', max_length=32, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Settings — Telegram Accounts',
            },
        ),
    ]
