# Generated by Django 4.2.7 on 2025-10-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0009_telegramaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('UPDATE_CHECKS', 'Update Checks from Integrations'), ('SCAN_PROBLEMS', 'Scan Problem Checks'), ('SEND_ANALYTICS', 'Send Analytics Report'), ('ANALYZE_PATTERNS', 'Analyze Check Patterns')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='task_type',
            field=models.CharField(choices=[('UPDATE_CHECKS', 'Update Checks from Integrations'), ('SCAN_PROBLEMS', 'Scan Problem Checks'), ('SEND_ANALYTICS', 'Send Analytics Report'), ('ANALYZE_PATTERNS', 'Analyze Check Patterns')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='CheckAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField(db_index=True, help_text='Start of the time window analyzed')),
                ('window_end', models.DateTimeField(db_index=True, help_text='End of the time window analyzed')),
                ('window_duration_minutes', models.PositiveIntegerField(help_text='Duration of the time window in minutes')),
                ('center_lat', models.FloatField(help_text='Center latitude of the analyzed area')),
                ('center_lon', models.FloatField(help_text='Center longitude of the analyzed area')),
                ('radius_meters', models.PositiveIntegerField(help_text='Radius of the analyzed area in meters')),
                ('total_checks', models.PositiveIntegerField(default=0, help_text='Total number of checks in this time/area window')),
                ('unique_expiditors', models.PositiveIntegerField(default=0, help_text='Number of unique expiditors in this window')),
                ('most_active_expiditor', models.CharField(blank=True, help_text='Name of the most active expiditor in this window', max_length=100, null=True)),
                ('most_active_count', models.PositiveIntegerField(default=0, help_text='Number of checks by the most active expiditor')),
                ('avg_checks_per_expiditor', models.FloatField(default=0.0, help_text='Average number of checks per expiditor')),
                ('analysis_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this analysis was performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Check Analytics',
                'ordering': ['-analysis_date', '-window_start'],
                'indexes': [models.Index(fields=['window_start', 'window_end'], name='expeditor_a_window__873cc1_idx'), models.Index(fields=['center_lat', 'center_lon'], name='expeditor_a_center__1ac027_idx'), models.Index(fields=['analysis_date'], name='expeditor_a_analysi_159532_idx')],
            },
        ),
    ]
