# Generated by Django 4.2.7 on 2025-10-14 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial_name', models.CharField(max_length=100, unique=True)),
                ('filial_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Filiallar',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sklad_name', models.CharField(max_length=100, unique=True)),
                ('sklad_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Skladlar',
            },
        ),
        migrations.CreateModel(
            name='Ekispiditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekispiditor_name', models.CharField(max_length=100, unique=True)),
                ('transport_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ekispiditors', to='expeditor_app.filial')),
            ],
            options={
                'verbose_name_plural': 'Ekispiditorlar',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True)),
                ('city_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='expeditor_app.filial')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='CheckDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(max_length=100, unique=True)),
                ('checkURL', models.URLField(unique=True)),
                ('check_date', models.DateTimeField(blank=True, null=True)),
                ('receiptIdDate', models.DateTimeField(blank=True, null=True)),
                ('check_lat', models.FloatField(blank=True, null=True)),
                ('check_lon', models.FloatField(blank=True, null=True)),
                ('total_sum', models.FloatField(blank=True, null=True)),
                ('nalichniy', models.FloatField(blank=True, null=True)),
                ('uzcard', models.FloatField(blank=True, null=True)),
                ('humo', models.FloatField(blank=True, null=True)),
                ('click', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Check Details',
                'indexes': [models.Index(fields=['check_id'], name='expeditor_a_check_i_fc9c36_idx'), models.Index(fields=['total_sum'], name='expeditor_a_total_s_c38059_idx'), models.Index(fields=['check_date'], name='expeditor_a_check_d_0dace5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(max_length=100, unique=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('sklad', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('sborshik', models.CharField(blank=True, max_length=100, null=True)),
                ('agent', models.CharField(blank=True, max_length=100, null=True)),
                ('ekispiditor', models.CharField(blank=True, max_length=100, null=True)),
                ('yetkazilgan_vaqti', models.DateTimeField(blank=True, null=True)),
                ('receiptIdDate', models.DateTimeField(blank=True, null=True)),
                ('transport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('kkm_number', models.CharField(blank=True, max_length=50, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('client_address', models.TextField(blank=True, null=True)),
                ('check_lat', models.FloatField(blank=True, null=True)),
                ('check_lon', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('delivered', 'Yetkazilgan'), ('failed', 'Muvaffaqiyatsiz'), ('pending', 'Kutilmoqda')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Checklar',
                'ordering': ['-yetkazilgan_vaqti'],
                'indexes': [models.Index(fields=['ekispiditor', 'status'], name='expeditor_a_ekispid_92be8b_idx'), models.Index(fields=['yetkazilgan_vaqti'], name='expeditor_a_yetkazi_eca927_idx'), models.Index(fields=['project'], name='expeditor_a_project_d3e998_idx'), models.Index(fields=['city'], name='expeditor_a_city_b32fdb_idx'), models.Index(fields=['sklad'], name='expeditor_a_sklad_fa5f47_idx'), models.Index(fields=['status', 'yetkazilgan_vaqti'], name='expeditor_a_status_42a3f3_idx'), models.Index(fields=['check_lat', 'check_lon'], name='expeditor_a_check_l_bd034d_idx')],
            },
        ),
    ]
