# Generated by Django 4.2.7 on 2025-07-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkdetail',
            name='receiptIdDate',
        ),
        migrations.AlterField(
            model_name='checkdetail',
            name='check_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
