# Generated by Django 4.2.7 on 2025-07-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekispiditor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
