# Generated by Django 4.2.7 on 2025-07-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0002_remove_checkdetail_receiptiddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkdetail',
            name='receiptIdDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
