# Generated by Django 4.2.7 on 2025-07-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0002_alter_ekispiditor_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='receiptIdDate',
        ),
    ]
