# Generated by Django 4.2.7 on 2025-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0003_remove_check_receiptiddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='receiptIdDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
