# Generated by Django 4.2.7 on 2025-10-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0005_integrationendpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Email Recipients',
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('task_type', models.CharField(choices=[('UPDATE_CHECKS', 'Update Checks from Integrations'), ('SCAN_PROBLEMS', 'Scan Problem Checks'), ('SEND_ANALYTICS', 'Send Analytics Report')], db_index=True, max_length=50)),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('params', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Scheduled Tasks',
                'indexes': [models.Index(fields=['is_enabled', 'next_run_at', 'task_type'], name='expeditor_a_is_enab_c4a773_idx')],
            },
        ),
    ]
