# Generated by Django 4.2.7 on 2025-07-25 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0005_filial_city_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekispiditor',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ekispiditors', to='expeditor_app.filial'),
        ),
    ]
