# Generated by Django 4.2.7 on 2025-10-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0006_emailrecipient_scheduledtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('UPDATE_CHECKS', 'Update Checks from Integrations'), ('SCAN_PROBLEMS', 'Scan Problem Checks'), ('SEND_ANALYTICS', 'Send Analytics Report')], db_index=True, max_length=50)),
                ('is_running', models.BooleanField(db_index=True, default=True)),
                ('status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Task Runs',
                'indexes': [models.Index(fields=['task_type', 'is_running', 'started_at'], name='expeditor_a_task_ty_4c1f36_idx')],
            },
        ),
    ]
