# Generated by Django 4.2.7 on 2025-10-17 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0007_taskrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=200)),
                ('host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Settings — Email Config',
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('default_params', models.JSONField(blank=True, null=True)),
                ('sample_result', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Settings — Task List',
            },
        ),
        migrations.AlterModelOptions(
            name='emailrecipient',
            options={'verbose_name_plural': 'Settings — Email Recipients'},
        ),
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'verbose_name_plural': 'Settings — Scheduled Tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskrun',
            options={'verbose_name_plural': 'Tasks — Runs'},
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_uses', to='expeditor_app.tasklist'),
        ),
    ]
