# Generated by Django 4.2.7 on 2025-10-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0010_alter_scheduledtask_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkanalytics',
            name='check_details',
            field=models.JSONField(blank=True, default=dict, help_text='Structured check details including locations and times'),
        ),
        migrations.AddField(
            model_name='checkanalytics',
            name='check_ids',
            field=models.JSONField(default=list, help_text='List of check IDs that were part of this analysis'),
        ),
    ]
