# Generated by Django 4.2.7 on 2025-10-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0011_checkanalytics_check_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YandexToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Token name for identification', max_length=100)),
                ('api_key', models.CharField(help_text='Yandex Maps API key', max_length=200, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], db_index=True, default='inactive', help_text='Token status', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Token description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Settings — Yandex Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
