# Generated by Django 4.2.7 on 2025-10-20 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
