# Generated by Django 4.2.7 on 2025-10-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0014_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='yandextoken',
            name='keyword',
            field=models.CharField(default='YANDEX_MAPS_API_KEY', help_text="Unique keyword for env file identification (e.g., 'YANDEX_MAPS_API_KEY')", max_length=50, unique=True),
        ),
    ]
