# Generated by Django 4.2.7 on 2025-10-21 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0011_update_scan_problems_description'),
        ('expeditor_app', '0015_yandextoken_keyword'),
    ]

    operations = [
    ]
