# Generated by Django 4.2.7 on 2025-10-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0017_fix_taskrun_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taskrun',
            new_name='expeditor_a_status_a1ef8a_idx',
            old_name='expeditor_a_status_idx',
        ),
    ]
