# Generated by Django 4.2.7 on 2025-10-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0018_rename_expeditor_a_status_idx_expeditor_a_status_a1ef8a_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
