# Generated by Django 4.2.7 on 2025-10-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0019_alter_taskrun_status_message_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkanalytics',
            name='violation_type',
            field=models.CharField(choices=[('TIME_DISTANCE', 'Time and Distance Based'), ('SAME_LOCATION', 'Same Location Same Day')], db_index=True, default='TIME_DISTANCE', help_text='Type of violation detected', max_length=20),
        ),
        migrations.AddIndex(
            model_name='checkanalytics',
            index=models.Index(fields=['violation_type', 'analysis_date'], name='expeditor_a_violati_78e81f_idx'),
        ),
    ]
