# Generated by Django 4.2.7 on 2025-10-24 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0020_checkanalytics_violation_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('user_type', models.CharField(choices=[('super_user', 'Super User'), ('regular_user', 'Regular User'), ('guest', 'Guest')], default='guest', max_length=20)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('map_interactions', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
                ('session_duration', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('page_view', 'Page View'), ('api_call', 'API Call'), ('map_interaction', 'Map Interaction'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('filter', 'Filter')], max_length=50)),
                ('page_url', models.URLField(blank=True, null=True)),
                ('api_endpoint', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='expeditor_app.usersession')),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='expeditor_a_session_539dff_idx'), models.Index(fields=['activity_type', 'timestamp'], name='expeditor_a_activit_91212e_idx')],
            },
        ),
    ]
