# Generated by Django 4.2.7 on 2025-10-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0021_usersession_useractivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramaccount',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name_plural': 'Telegram Accounts'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'User Activities'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-last_activity'], 'verbose_name_plural': 'User Sessions'},
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='expeditor_a_session_539dff_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='expeditor_a_activit_91212e_idx',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='additional_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='username',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='api_endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='api_calls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='map_interactions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='page_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='total_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_type',
            field=models.CharField(default='guest', max_length=50),
        ),
    ]
