# Generated by Django 4.2.7 on 2025-12-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditor_app', '0022_alter_telegramaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='lat',
            field=models.FloatField(blank=True, help_text='Sklad address latitude', null=True),
        ),
        migrations.AddField(
            model_name='sklad',
            name='lon',
            field=models.FloatField(blank=True, help_text='Sklad address longitude', null=True),
        ),
    ]
