"use client"

import { createContext, useContext, useEffect, useState, ReactNode } from "react"

export type Language = 'uz' | 'ru' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation keys
const translations = {
  uz: {
    // Main page
    'expeditor_tracker': 'Ekspeditor Kuzatuvchi',
    'update_data': 'Ma\'lumotlarni yangilash',
    'last_update': 'Oxirgi yangilanish',
    'date_range': 'Sana oralig\'i',
    'today': 'Bugun',
    'selected': 'Tanlangan',
    'filter': 'Filter',
    'search_expeditors': 'Ekspeditorlarni qidirish...',
    'no_expeditors_found': 'Ekspeditorlar topilmadi',
    'try_changing_filter': 'Filterni o\'zgartirib ko\'ring',
    'checks_count': 'Cheklar',
    'uzs': 'UZS',
    'filial': 'Filial',
    'phone': 'Telefon',
    'transport': 'Transport',
    'status': 'Holat',
    'project': 'Loyiha',
    'warehouse': 'Ombor',
    'city': 'Shahar',
    'all_projects': 'Barcha loyihalar',
    'all_warehouses': 'Barcha omborlar',
    'all_cities': 'Barcha shaharlar',
    'all_statuses': 'Barcha holatlar',
    'clear_all_filters': 'Barcha filterlarni tozalash',
    'active_filters': 'Faol filterlar',
    'daily_routes': 'Kunlik yo\'nalishlar',
    'statistics': 'Statistika',
    'total_checks': 'Jami cheklar',
    'total_amount': 'Jami summa',
    'unique_expeditors': 'Ekspeditorlar',
    'average_checks': 'O\'rtacha cheklar',
    'show_stats': 'Statistikani ko\'rsatish',
    'hide_stats': 'Statistikani yashirish',
    'language': 'Til',
    'select_expeditor_to_view_checks': 'Cheklarni ko\'rish uchun ekspeditor tanlang',
    'loading_checks': 'Cheklar yuklanmoqda...',
    'no_checks_found': 'Cheklar topilmadi',
    'try_adjusting_filters': 'Sana oralig\'i yoki filterlarni o\'zgartiring',
    'loading_expeditors': 'Ekspeditorlar yuklanmoqda...',
    'success_rate': 'Muvaffaqiyat darajasi',
    'payment_methods': 'To\'lov usullari',
    'cash': 'Naqd pul',
    'uzcard': 'UzCard',
    'humo': 'Humo',
    'click': 'Click',
    'enhanced_analytics_dashboard': 'Kengaytirilgan Analytics Dashboard',
    'main_dashboard': 'Asosiy Dashboard',
    'telegram_contact_dev': 'Telegram (Dev bilan aloqa)',
    'user_analytics': 'Foydalanuvchi tahlili',
    'sort_by': 'Saralash',
    'sort_name': 'Ism',
    'sort_phone': 'Telefon',
    'sort_transport': 'Transport',
    'sort_filial': 'Filial',
    'sort_checks_count': 'Cheklar soni',
    'sort_order': 'Tartib',
    'sort_ascending': 'O\'sish (A-Z)',
    'sort_descending': 'Kamayish (Z-A)',
    'analytics_violations': 'Analytics va Buzilishlar',
    'enhanced_analytics': 'Kengaytirilgan Analytics',
    'violation_analytics': 'Buzilish Analytics',
    'same_location_violations': 'Bir xil joy buzilishlari',
    'buzilishlar_nazorati': 'Buzilishlar Nazorati',
    'tasks_management': 'Vazifalar boshqaruvi',
    'user_analytics': 'Foydalanuvchi Analytics',
    'yandex_tokens': 'Yandex Tokens',
    'check_pattern_analysis': 'Check naqshlarini tahlil qilish - Vaqt oynalari va geografik klasterlar',
    'logout': 'Chiqish',
    'real_time_analysis_fraud_detection': 'Real vaqt tahlili va fraud aniqlash',
    'comprehensive_statistics_insights': 'Kengaytirilgan statistika va ekspeditor ishlashi uchun tahlil',
    'export_all': 'Hammasini eksport qilish',
    'refresh': 'Yangilash',
    'advanced_filters': 'Kengaytirilgan filterlar',
    'active': 'faol',
    'visible': 'ko\'rinadi',
    'delivered': 'Yetkazilgan',
    'failed': 'Muvaffaqiyatsiz',
    'pending': 'Kutilmoqda',
    'all_expeditor_checks': 'Barcha ekspeditor cheklari',
    'successfully_delivered': 'Muvaffaqiyatli yetkazilgan',
    'failed_deliveries': 'Muvaffaqiyatsiz yetkazishlar',
    'awaiting_delivery': 'Yetkazishni kutmoqda',
    'total_check_value': 'Jami check qiymati',
    'average_check': 'O\'rtacha check',
    'per_check_average': 'Har bir check uchun o\'rtacha',
    'delivery_success_rate': 'Yetkazish muvaffaqiyat darajasi',
    'todays_checks': 'Bugungi cheklar',
    'top_expeditors': 'Eng yaxshi ekspeditorlar',
    'top_projects': 'Eng yaxshi loyihalar',
    'top_cities': 'Eng yaxshi shaharlar',
    'total_sum_uzs': 'Jami summa (UZS)',
    'average_check_sum_uzs': 'O\'rtacha check summasi (UZS)',
    'success_rate_percent': 'Muvaffaqiyat darajasi (%)',
    'export': 'Eksport qilish',
    'daily_check_distribution': 'Kunlik check taqsimoti',
    'top_expeditors_by_check_count': 'Eng yaxshi ekspeditorlar (check soni bo\'yicha)',
    'top_projects_by_check_count': 'Eng yaxshi loyihalar (check soni bo\'yicha)',
    'top_cities_by_check_count': 'Eng yaxshi shaharlar (check soni bo\'yicha)',
    'chart_visibility_settings': 'Chart ko\'rinish sozlamalari',
    'dailyStats': 'Kunlik statistika',
    'hourlyStats': 'Soatlik statistika',
    'topExpeditors': 'Eng yaxshi ekspeditorlar',
    'topProjects': 'Eng yaxshi loyihalar',
    'topCities': 'Eng yaxshi shaharlar',
    'paymentMethods': 'To\'lov usullari',
    'loading_enhanced_statistics_page': 'Kengaytirilgan statistika sahifasi yuklanmoqda...',
    'filters': 'Filterlar',
    'date_from': 'Boshlanish sanasi',
    'date_to': 'Tugash sanasi',
    'expeditor': 'Ekspeditor',
    'min_checks': 'Minimal cheklar',
    'max_checks': 'Maksimal cheklar',
    'radius_meters': 'Radius (metr)',
    'select_radius': 'Radius tanlang',
    'window_duration_min': 'Oyna davomiyligi (min)',
    'select_duration': 'Davomiylikni tanlang',
    'clear_filters': 'Filterlarni tozalash',
    'analytics_summary': 'Analytics xulosa',
    'time_window': 'Vaqt oynasi',
    'most_active': 'Eng faol',
    'total_records': 'Jami yozuvlar',
    'avg_checks_window': 'O\'rtacha cheklar/oyna',
    'analytics_data': 'Analytics ma\'lumotlari',
    'per_page': 'Har sahifada',
    'showing': 'Ko\'rsatilmoqda',
    'to': 'dan',
    'of': 'dan',
    'records': 'yozuvlar',
    'view_details': 'Tafsilotlarni ko\'rish',
    'violation_details': 'Buzilish tafsilotlari',
    'check_details': 'Check tafsilotlari',
    'location': 'Joylashuv',
    'most_active_expeditor': 'Eng faol ekspeditor',
    'area': 'Hudud',
    'actions': 'Amallar',
    'date_time': 'Sana va vaqt',
    'previous': 'Oldingi',
    'next': 'Keyingi',
    'page': 'Sahifa',
    'success': 'Muvaffaqiyat',
    'error': 'Xatolik',
    'data_refreshed_successfully': 'Ma\'lumotlar muvaffaqiyatli yangilandi',
    'failed_to_load_analytics_data': 'Analytics ma\'lumotlarini yuklashda xatolik',
    'report_exported_successfully': 'Hisobot muvaffaqiyatli eksport qilindi',
    'failed_to_load_violation_checks': 'Buzilish cheklarini yuklashda xatolik',
    'loading_analytics_dashboard': 'Analytics dashboard yuklanmoqda...',
    'no_analytics_data_available': 'Analytics ma\'lumotlari mavjud emas',
    'retry': 'Qayta urinish',
    'violation_analytics': 'Buzilish Analytics',
    'real_time_pattern_detection_analysis': 'Real vaqt naqsh aniqlash va tahlil',
    'apply_filters': 'Filterlarni qo\'llash',
    'clear_all': 'Barchasini tozalash',
    'total_violations': 'Jami buzilishlar',
    'checks_involved': 'Jami cheklar',
    'expeditors_count': 'Ekspeditorlar',
    'avg_radius': 'O\'rtacha radius',
    'top_violators': 'Eng ko\'p buzilish qiluvchilar',
    'violators': 'Buzilish qiluvchilar',
    'violation_checks': 'Buzilish cheklari',
    'geography': 'Geografiya',
    'map': 'Xarita',
    'time': 'Vaqt',
    'severity': 'Jiddiylik',
    'level': 'Daraja',
    'trends': 'Trendlar',
    'trend': 'Trend',
    'min_radius': 'Minimal radius (m)',
    'max_radius': 'Maksimal radius (m)',
    'violation_checks_data': 'Buzilish cheklari ma\'lumotlari',
    'click_to_load_violation_checks': 'Buzilish cheklarini yuklash uchun bosing',
    'client': 'Mijoz',
    'total_sum': 'Jami summa',
    'top_10_violators': 'Top 10 buzilish qiluvchilar',
    'most_frequent_violation_patterns': 'Eng tez-tez uchraydigan buzilish naqshlari',
    'avg': 'O\'rtacha',
    'violations_count': 'buzilishlar',
    'click_for_details': 'Tafsilotlar uchun bosing',
    'performance_metrics': 'Ishlash ko\'rsatkichlari',
    'detailed_expeditor_statistics': 'Batafsil ekspeditor statistikasi',
    'avg_v': 'O\'rtacha/B',
    'geographic_hotspots': 'Geografik issiq nuqtalar',
    'areas_with_highest_violation_density': 'Eng yuqori buzilish zichligi bo\'lgan hududlar',
    'time_analysis': 'Vaqt tahlili',
    'violation_patterns_by_time_periods': 'Vaqt davrlari bo\'yicha buzilish naqshlari',
    'daily_distribution': 'Kunlik taqsimot',
    'violations_by_day_of_week': 'Hafta kunlari bo\'yicha buzilishlar',
    'hourly_pattern': 'Soatlik naqsh',
    'peak_violation_hours': 'Eng ko\'p buzilish soatlari',
    'severity_levels': 'Jiddiylik darajalari',
    'categorized_by_violation_radius': 'Buzilish radiusi bo\'yicha tasniflash',
    'critical': 'Jiddiy',
    'warning': 'Ogohlantirish',
    'minor': 'Kichik',
    'meters': 'metr',
    'daily_trend_analysis': 'Kunlik trend tahlili',
    'violation_trends_over_time': 'Vaqt o\'tishi bilan buzilish trendlari',
    'filters': 'Filterlar',
    'refresh': 'Yangilash',
    'updated': 'Yangilandi',
    'data_updated': 'Ma\'lumotlar yangilandi',
    'failed_to_load_data': 'Ma\'lumotlarni yuklashda xatolik',
    'from_date': 'Sanadan',
    'to_date': 'Sanagacha',
    'expeditor': 'Ekspiditor',
    'all': 'Barchasi',
    'min_checks': 'Min Cheklar',
    'search': 'Qidirish',
    'total_violations': 'Jami Buzilishlar',
    'suspicious_patterns': 'Shubhali Holatlar',
    'unique_expeditors': 'Ekspiditorlar',
    'total_checks': 'Jami Cheklar',
    'top_violators_by_risk': 'Eng Ko\'p Buzilish Qilgan Ekspiditorlar (TOP 10)',
    'sorted_by_risk_level': 'Risk darajasi bo\'yicha tartiblangan',
    'unknown': 'Noma\'lum',
    'checks': 'chek',
    'violations': 'buzilish',
    'suspicious': 'shubhali',
    'critical': 'kritik',
    'view': 'Ko\'rish',
    'daily_violations': 'Kunlik Buzilishlar',
    'grouped_by_date': 'Sana bo\'yicha gruppalangan buzilishlar',
    'no_data_found': 'Ma\'lumot topilmadi',
    'violations_count': 'buzilish',
    'checks_count': 'chek',
    'location_clusters_next_version': 'Joylashuv klasterlari keyingi versiyada qo\'shiladi',
    'buzilishlar_nazorati': 'Buzilishlar Nazorati',
    'real_time_analysis_fraud_detection': 'Real vaqtda tahlil va firibgarlikni aniqlash',
    'filters': 'Filtrlar',
    'refresh': 'Yangilash',
    'updated': 'Yangilandi',
    'data_updated': 'Ma\'lumotlar yangilandi',
    'failed_to_load_data': 'Ma\'lumotlarni yuklashda xatolik',
    'from_date': 'Boshlanish sanasi',
    'to_date': 'Tugash sanasi',
    'expeditor': 'Ekspiditor',
    'all': 'Barchasi',
    'min_checks': 'Minimal cheklar',
    'search': 'Qidirish',
    'total_violations': 'Jami Buzilishlar',
    'suspicious_patterns': 'Shubhali Holatlar',
    'unique_expeditors': 'Ekspiditorlar',
    'total_checks': 'Jami Cheklar',
    'top_violators_by_risk': 'Eng Ko\'p Buzilish Qilgan Ekspiditorlar (TOP 10)',
    'sorted_by_risk_level': 'Xavf darajasiga qarab tartiblangan',
    'unknown': 'Noma\'lum',
    'checks': 'cheklar',
    'violations': 'buzilishlar',
    'suspicious': 'shubhali',
    'critical': 'jiddiy',
    'view': 'Ko\'rish',
    'daily_violations': 'Kunlik Buzilishlar',
    'grouped_by_date': 'Sana bo\'yicha gruppalangan buzilishlar',
    'no_data_found': 'Ma\'lumot topilmadi',
    'violations_count': 'buzilish',
    'checks_count': 'chek',
    'location_clusters_next_version': 'Joylashuv klasterlari keyingi versiyada qo\'shiladi',
    'no_checks_found_for_this_day': 'Bu kun uchun cheklar topilmadi',
    'checks_for_this_day': 'Bu kundagi cheklar',
    'violations_short': 'buzilish',
    'clear_selection': 'Tanlovni tozalash - Umumiy statistika',
    'colors_legend': 'Ranglar:',
    'violations_explanation': 'Buzilish deb nima hisoblanadi:',
    'suspicious_explanation': 'Shubhali deb qanday cheklar topiladi:',
    'gps_coordinates_wrong': 'GPS koordinatalari noto\'g\'ri yoki yo\'q',
    'expeditor_wrong_location': 'Chek vaqtida ekspiditor boshqa joyda bo\'lgan',
    'meeting_time_mismatch': 'Mijoz bilan uchrashuv vaqtida ekspiditor u yerda emas',
    'gps_signal_lost': 'GPS signali uzilgan yoki zaif',
    'route_deviation': 'Ekspiditor marshrutdan chetga chiqqan',
    'moving_during_check': 'Chek vaqtida ekspiditor harakatlanayotgan',
    'same_location_multiple_checks': 'Bir xil joyda ko\'p marta chek qilingan',
    'multiple_locations_simultaneously': 'Ekspiditor bir vaqtning o\'zida bir necha joyda',
    'frequent_gps_disconnection': 'Tez-tez GPS signali uzilayotgan',
    'constant_route_deviation': 'Marshrutdan doimiy ravishda chetga chiqish',
    'unusual_check_patterns': 'Chek vaqtlari notabiiy naqsh ko\'rsatadi',
    'too_many_or_few_checks': 'Bir kunda juda ko\'p yoki juda kam cheklar',
    'gps_coordinates_stuck': 'GPS koordinatalari bir xil joyda qolib ketgan',
    // User Guide Page
    'user_guide_title': 'Foydalanuvchilar Qo\'llanmasi',
    'user_guide_subtitle': 'Expeditor Tracker tizimini qanday ishlatishni o\'rganing',
    'basic_functions': 'Asosiy Funksiyalar',
    'filtering_and_search': 'Filtrlash va Qidiruv',
    'statistics_and_analytics': 'Statistika va Analitika',
    'what_is_project': 'Proyekt Nima?',
    'map_tracking': 'Xaritada Kuzatish',
    'statistics_and_analysis': 'Statistika va Tahlil',
    'advanced_filtering': 'Kengaytirilgan Filtrlash',
    'real_time_updates': 'Real Vaqtda Yangilanish',
    'map_section': 'Xarita (Map)',
    'expeditors_list': 'Ekspeditorlar Ro\'yxati',
    'checks_list': 'Checklar Ro\'yxati',
    'statistics_panel': 'Statistika Paneli',
    'green_successful': 'Yashil = Muvaffaqiyatli',
    'red_problem': 'Qizil = Muammo',
    'yellow_pending': 'Sariq = Kutayotgan',
    'what_to_do': 'Nima qilish kerak:',
    'date_range_filter': 'Sana Oralig\'i',
    'project_filter': 'Loyiha (Project)',
    'warehouse_filter': 'Ombor (Sklad)',
    'city_filter': 'Shahar (City)',
    'status_filter': 'Status',
    'search_filter': 'Qidiruv',
    'how_to_use': 'Qanday ishlatish:',
    'main_statistics': 'Asosiy Statistika',
    'enhanced_analytics': 'Kengaytirilgan Analitika',
    'violation_analytics_title': 'Violation Analytics (Buzilishlar Analitikasi)',
    'check_details_title': 'Check Haqida Batafsil Ma\'lumot',
    'update_data_title': 'Ma\'lumotlarni Yangilash',
    'mobile_usage': 'Mobil Qurilmalarda Ishlatish',
    'telegram_webapp': 'Telegram WebApp',
    'mobile_browser': 'Mobil Brauzer',
    'faq_title': 'Tez-tez Beriladigan Savollar',
    'tips_title': 'Foydalanish Tavsiyalari',
    'back_to_home': 'Asosiy Sahifaga Qaytish',
    'check_id': 'Check ID',
    'client_name_address': 'Mijoz ismi va manzili',
    'delivery_time': 'Yetkazib berilgan vaqt',
    'total_amount': 'Jami summa',
    'payment_methods_detail': 'To\'lov usullari (Naqd, UzCard, Humo, Click)',
    'gps_coordinates': 'GPS koordinatalar',
    'what_is_check': 'Q: Check nima?',
    'check_answer': 'A: Check - bu yetkazib berish (delivery). Har bir buyurtma bir check hisoblanadi.',
    'what_is_expeditor': 'Q: Ekspeditor nima?',
    'expeditor_answer': 'A: Ekspeditor - yetkazib berish xodimi. Ular buyurtmalarni mijozlarga yetkazib beradi.',
    'map_no_points': 'Q: Xaritada nuqtalar ko\'rinmayapti?',
    'map_no_points_answer': 'A: Filtrlarni tekshiring. Ekspeditor tanlanganligini tekshiring. Sana oralig\'ini tekshiring.',
    'data_not_updating': 'Q: Ma\'lumotlar yangilanmayapti?',
    'data_not_updating_answer': 'A: "Refresh" tugmasini bosing. Yoki "Update Data" tugmasini bosing. Bir necha soniya kuting.',
    'stats_not_showing': 'Q: Statistika ko\'rinmayapti?',
    'stats_not_showing_answer': 'A: "Statistics" tugmasini bosing. Yoki statistika panelini oching. Filtrlarni tekshiring.',
    'save_filters': 'Filtrlarni saqlang',
    'save_filters_desc': 'Filtrlarni to\'ldiring. Tizim avtomatik saqlaydi. Keyingi safar avtomatik yuklanadi.',
    'select_expeditor': 'Ekspeditorni tanlang',
    'select_expeditor_desc': 'Ekspeditor ustiga bosing. Faqat uning checklari ko\'rinadi. Xaritada faqat uning checklari ko\'rsatiladi.',
    'use_map': 'Xaritadan foydalaning',
    'use_map_desc': 'Marker ustiga bosing. Batafsil ma\'lumot ko\'ring. Xaritada harakatlaning.',
    'use_statistics': 'Statistikadan foydalaning',
    'use_statistics_desc': 'Statistika panelini oching. Ma\'lumotlarni tahlil qiling. Hisobotlar tayyorlang.',
    'filter_description': 'Filtrlash tugmasini bosib, quyidagi filtrlardan foydalaning:',
    'date_range_desc': '"From" (dan) va "To" (gacha) - boshlanish va tugash sanalarini tanlang. Kalendardan tanlash mumkin.',
    'project_filter_desc': 'Dropdown dan loyihani tanlang yoki "All" (Hammasi) ni tanlang.',
    'warehouse_filter_desc': 'Dropdown dan omborni tanlang yoki "All" ni tanlang.',
    'city_filter_desc': 'Dropdown dan shaharni tanlang yoki "All" ni tanlang.',
    'status_filter_desc': 'Delivered (Yetkazilgan), Failed (Noto\'g\'ri), Pending (Kutayotgan) yoki "All" ni tanlang.',
    'search_filter_desc': 'Check ID yoki mijoz ismini yozing. Avtomatik qidiriladi.',
    'how_to_use_filters': 'Filtrlarni to\'ldiring → "Apply" (Qo\'llash) tugmasini bosing → Natijalar yangilanadi. Filtrlarni tozalash uchun "Clear" (Tozalash) tugmasini bosing.',
    'map_description': 'Asosiy sahifada markazda katta xarita ko\'rinadi. Xaritada rangli nuqtalar (markerlar) - bu checklar (yetkazib berishlar).',
    'map_what_to_do': 'Marker ustiga bosing - check haqida batafsil ma\'lumot ko\'rinadi. Xaritani surib ko\'ring (zoom in/out).',
    'expeditors_list_desc': 'Barcha ekspeditorlar ro\'yxati ko\'rinadi. Har bir ekspeditor yonida:',
    'expeditors_list_items': 'Ism, Bugungi checklar soni, Jami checklar soni, Rasm (agar bor bo\'lsa)',
    'expeditors_what_to_do': 'Ekspeditor ustiga bosing - uning checklari ko\'rinadi. Qidiruv bo\'limida ism yozib qidiring.',
    'checks_list_desc': 'Tanlangan ekspeditorning barcha checklari ko\'rinadi. Har bir checkda:',
    'checks_list_items': 'Check ID (raqam), Mijoz ismi, Manzil, Vaqt, Summa, Status (muvaffaqiyatli/noto\'g\'ri)',
    'checks_what_to_do': 'Check ustiga bosing - batafsil ma\'lumot ochiladi. Qidiruv bo\'limida check ID yozib qidiring.',
    'statistics_panel_desc': 'Statistika panelida quyidagi ma\'lumotlar ko\'rinadi:',
    'statistics_panel_items': 'Jami checklar soni, Jami summa, To\'lov usullari bo\'yicha taqsimot (Naqd, UzCard, Humo, Click), Muvaffaqiyat darajasi (%)',
    'statistics_what_to_do': '"Statistics" tugmasini bosing (yoki avtomatik ochiladi). Ma\'lumotlarni ko\'ring va tahlil qiling.',
    'check_details_desc': 'Check ustiga bosganingizda modal oyna ochiladi va quyidagi ma\'lumotlar ko\'rinadi:',
    'check_details_what_to_do': 'Ma\'lumotlarni ko\'ring → "Close" (Yopish) tugmasini bosing. Yoki xaritada ko\'rsatish uchun "Show on Map" tugmasini bosing.',
    'update_data_desc': 'Ma\'lumotlarni yangilash uchun:',
    'update_data_steps': '1. Yuqoridagi "Refresh" (🔄) tugmasini bosing\n2. Yoki "Update Data" tugmasini bosing\n3. Progress bar ko\'rinadi\n4. Ma\'lumotlar yangilanadi',
    'update_data_note': 'Yangilanish bir necha soniya davom etishi mumkin. Katta ma\'lumotlar bo\'lsa, uzoqroq vaqt olishi mumkin.',
    'telegram_webapp_desc': 'Telegram bot orqali kirish. Yoki brauzerda ochish. Interfeys mobil uchun moslashtirilgan.',
    'mobile_browser_desc': 'Saytga kirish. Interfeys avtomatik moslashadi. Barcha funksiyalar ishlaydi.',
    'main_statistics_desc': 'Asosiy sahifada statistika paneli mavjud. Yoki "Statistics" tugmasini bosing.',
    'main_statistics_items': 'Jami checklar soni, Jami summa, Muvaffaqiyat darajasi (%), To\'lov usullari bo\'yicha taqsimot, Eng yaxshi ekspeditorlar, Eng yaxshi loyihalar',
    'enhanced_analytics_desc': 'Yuqoridagi "Analytics" tugmasini bosing yoki "Enhanced Analytics" ni tanlang.',
    'enhanced_analytics_items': 'Grafiklar va diagrammalar, Trendlar, Tahlillar, Export qilish imkoniyati',
    'violation_analytics_desc': '"Violation Analytics" tugmasini bosing.',
    'violation_analytics_items': 'Muammoli checklar, Bir xil joydagi buzilishlar, Buzilishlar statistikasi, Tahlillar',
  },
  ru: {
    // Main page
    'expeditor_tracker': 'Трекер Экспедиторов',
    'update_data': 'Обновить данные',
    'last_update': 'Последнее обновление',
    'date_range': 'Диапазон дат',
    'today': 'Сегодня',
    'selected': 'Выбрано',
    'filter': 'Фильтр',
    'search_expeditors': 'Поиск экспедиторов...',
    'no_expeditors_found': 'Экспедиторы не найдены',
    'try_changing_filter': 'Попробуйте изменить фильтр',
    'checks_count': 'Чеки',
    'uzs': 'UZS',
    'filial': 'Филиал',
    'phone': 'Телефон',
    'transport': 'Транспорт',
    'status': 'Статус',
    'project': 'Проект',
    'warehouse': 'Склад',
    'city': 'Город',
    'all_projects': 'Все проекты',
    'all_warehouses': 'Все склады',
    'all_cities': 'Все города',
    'all_statuses': 'Все статусы',
    'clear_all_filters': 'Очистить все фильтры',
    'active_filters': 'Активные фильтры',
    'daily_routes': 'Ежедневные маршруты',
    'statistics': 'Статистика',
    'total_checks': 'Всего чеков',
    'total_amount': 'Общая сумма',
    'unique_expeditors': 'Экспедиторы',
    'average_checks': 'Средние чеки',
    'show_stats': 'Показать статистику',
    'hide_stats': 'Скрыть статистику',
    'language': 'Язык',
    'select_expeditor_to_view_checks': 'Выберите экспедитора для просмотра чеков',
    'loading_checks': 'Загрузка чеков...',
    'no_checks_found': 'Чеки не найдены',
    'try_adjusting_filters': 'Попробуйте изменить диапазон дат или фильтры',
    'loading_expeditors': 'Загрузка экспедиторов...',
    'success_rate': 'Уровень успеха',
    'payment_methods': 'Способы оплаты',
    'cash': 'Наличные',
    'uzcard': 'UzCard',
    'humo': 'Humo',
    'click': 'Click',
    'enhanced_analytics_dashboard': 'Расширенная аналитическая панель',
    'main_dashboard': 'Главная панель',
    'telegram_contact_dev': 'Telegram (Связаться с разработчиком)',
    'user_analytics': 'Аналитика пользователей',
    'sort_by': 'Сортировка',
    'sort_name': 'Имя',
    'sort_phone': 'Телефон',
    'sort_transport': 'Транспорт',
    'sort_filial': 'Филиал',
    'sort_checks_count': 'Количество чеков',
    'sort_order': 'Порядок',
    'sort_ascending': 'По возрастанию (А-Я)',
    'sort_descending': 'По убыванию (Я-А)',
    'analytics_violations': 'Аналитика и нарушения',
    'enhanced_analytics': 'Расширенная аналитика',
    'violation_analytics': 'Аналитика нарушений',
    'same_location_violations': 'Нарушения в одном месте',
    'buzilishlar_nazorati': 'Контроль нарушений',
    'tasks_management': 'Управление задачами',
    'user_analytics': 'Аналитика пользователей',
    'yandex_tokens': 'Yandex токены',
    'check_pattern_analysis': 'Анализ паттернов чеков - Временные окна и географические кластеры',
    'logout': 'Выйти',
    'real_time_analysis_fraud_detection': 'Анализ в реальном времени и обнаружение мошенничества',
    'comprehensive_statistics_insights': 'Комплексная статистика и аналитика производительности экспедиторов',
    'export_all': 'Экспорт всего',
    'refresh': 'Обновить',
    'advanced_filters': 'Расширенные фильтры',
    'active': 'активно',
    'visible': 'видимо',
    'delivered': 'Доставлено',
    'failed': 'Неудачно',
    'pending': 'В ожидании',
    'all_expeditor_checks': 'Все чеки экспедиторов',
    'successfully_delivered': 'Успешно доставлено',
    'failed_deliveries': 'Неудачные доставки',
    'awaiting_delivery': 'Ожидает доставки',
    'total_check_value': 'Общая стоимость чеков',
    'average_check': 'Средний чек',
    'per_check_average': 'Среднее за чек',
    'delivery_success_rate': 'Уровень успеха доставки',
    'todays_checks': 'Чеки сегодня',
    'top_expeditors': 'Топ экспедиторы',
    'top_projects': 'Топ проекты',
    'top_cities': 'Топ города',
    'total_sum_uzs': 'Общая сумма (UZS)',
    'average_check_sum_uzs': 'Средняя сумма чека (UZS)',
    'success_rate_percent': 'Уровень успеха (%)',
    'export': 'Экспорт',
    'daily_check_distribution': 'Ежедневное распределение чеков',
    'top_expeditors_by_check_count': 'Топ экспедиторы (по количеству чеков)',
    'top_projects_by_check_count': 'Топ проекты (по количеству чеков)',
    'top_cities_by_check_count': 'Топ города (по количеству чеков)',
    'chart_visibility_settings': 'Настройки видимости графиков',
    'dailyStats': 'Ежедневная статистика',
    'hourlyStats': 'Почасовая статистика',
    'topExpeditors': 'Топ экспедиторы',
    'topProjects': 'Топ проекты',
    'topCities': 'Топ города',
    'paymentMethods': 'Способы оплаты',
    'loading_enhanced_statistics_page': 'Загрузка расширенной страницы статистики...',
    'filters': 'Фильтры',
    'date_from': 'Дата от',
    'date_to': 'Дата до',
    'expeditor': 'Экспедитор',
    'min_checks': 'Мин. чеки',
    'max_checks': 'Макс. чеки',
    'radius_meters': 'Радиус (метры)',
    'select_radius': 'Выберите радиус',
    'window_duration_min': 'Длительность окна (мин)',
    'select_duration': 'Выберите длительность',
    'clear_filters': 'Очистить фильтры',
    'analytics_summary': 'Сводка аналитики',
    'time_window': 'Временное окно',
    'most_active': 'Самый активный',
    'total_records': 'Всего записей',
    'avg_checks_window': 'Среднее чеков/окно',
    'analytics_data': 'Данные аналитики',
    'per_page': 'На странице',
    'showing': 'Показано',
    'to': 'до',
    'of': 'из',
    'records': 'записей',
    'view_details': 'Просмотр',
    'violation_details': 'Детали нарушений',
    'check_details': 'Детали чеков',
    'location': 'Местоположение',
    'most_active_expeditor': 'Самый активный экспедитор',
    'area': 'Область',
    'actions': 'Действия',
    'date_time': 'Дата и время',
    'previous': 'Предыдущая',
    'next': 'Следующая',
    'page': 'Страница',
    'success': 'Успех',
    'error': 'Ошибка',
    'data_refreshed_successfully': 'Данные успешно обновлены',
    'failed_to_load_analytics_data': 'Ошибка загрузки данных аналитики',
    'report_exported_successfully': 'Отчет успешно экспортирован',
    'failed_to_load_violation_checks': 'Ошибка загрузки чеков нарушений',
    'loading_analytics_dashboard': 'Загрузка панели аналитики...',
    'no_analytics_data_available': 'Данные аналитики недоступны',
    'retry': 'Повторить',
    'violation_analytics': 'Аналитика нарушений',
    'real_time_pattern_detection_analysis': 'Обнаружение и анализ паттернов в реальном времени',
    'apply_filters': 'Применить фильтры',
    'clear_all': 'Очистить все',
    'total_violations': 'Всего нарушений',
    'checks_involved': 'Задействованные чеки',
    'expeditors_count': 'Экспедиторы',
    'avg_radius': 'Средний радиус',
    'top_violators': 'Топ нарушители',
    'violators': 'Нарушители',
    'violation_checks': 'Чеки нарушений',
    'geography': 'География',
    'map': 'Карта',
    'time': 'Время',
    'severity': 'Серьезность',
    'level': 'Уровень',
    'trends': 'Тренды',
    'trend': 'Тренд',
    'min_radius': 'Минимальный радиус (м)',
    'max_radius': 'Максимальный радиус (м)',
    'violation_checks_data': 'Данные чеков нарушений',
    'click_to_load_violation_checks': 'Нажмите для загрузки чеков нарушений',
    'client': 'Клиент',
    'total_sum': 'Общая сумма',
    'top_10_violators': 'Топ 10 нарушителей',
    'most_frequent_violation_patterns': 'Наиболее частые паттерны нарушений',
    'avg': 'Среднее',
    'violations_count': 'нарушения',
    'click_for_details': 'Нажмите для деталей',
    'performance_metrics': 'Метрики производительности',
    'detailed_expeditor_statistics': 'Подробная статистика экспедиторов',
    'avg_v': 'Среднее/Н',
    'geographic_hotspots': 'Географические горячие точки',
    'areas_with_highest_violation_density': 'Области с наибольшей плотностью нарушений',
    'time_analysis': 'Анализ времени',
    'violation_patterns_by_time_periods': 'Паттерны нарушений по временным периодам',
    'daily_distribution': 'Ежедневное распределение',
    'violations_by_day_of_week': 'Нарушения по дням недели',
    'hourly_pattern': 'Почасовой паттерн',
    'peak_violation_hours': 'Часы пиковых нарушений',
    'severity_levels': 'Уровни серьезности',
    'categorized_by_violation_radius': 'Категоризация по радиусу нарушения',
    'critical': 'Критический',
    'warning': 'Предупреждение',
    'minor': 'Незначительный',
    'meters': 'метры',
    'daily_trend_analysis': 'Анализ ежедневных трендов',
    'violation_trends_over_time': 'Тренды нарушений во времени',
    'filters': 'Фильтры',
    'refresh': 'Обновить',
    'updated': 'Обновлено',
    'data_updated': 'Данные обновлены',
    'failed_to_load_data': 'Ошибка загрузки данных',
    'from_date': 'С даты',
    'to_date': 'До даты',
    'expeditor': 'Экспедитор',
    'all': 'Все',
    'min_checks': 'Мин. чеки',
    'search': 'Поиск',
    'total_violations': 'Всего нарушений',
    'suspicious_patterns': 'Подозрительные случаи',
    'unique_expeditors': 'Экспедиторы',
    'total_checks': 'Всего чеков',
    'top_violators_by_risk': 'Топ нарушители по риску (ТОП 10)',
    'sorted_by_risk_level': 'Отсортированы по уровню риска',
    'unknown': 'Неизвестно',
    'checks': 'чек',
    'violations': 'нарушение',
    'suspicious': 'подозрительный',
    'critical': 'критический',
    'view': 'Просмотр',
    'daily_violations': 'Ежедневные нарушения',
    'grouped_by_date': 'Нарушения, сгруппированные по дате',
    'no_data_found': 'Данные не найдены',
    'violations_count': 'нарушение',
    'checks_count': 'чек',
    'location_clusters_next_version': 'Кластеры местоположений будут добавлены в следующей версии',
    'buzilishlar_nazorati': 'Контроль нарушений',
    'real_time_analysis_fraud_detection': 'Анализ в реальном времени и обнаружение мошенничества',
    'filters': 'Фильтры',
    'refresh': 'Обновить',
    'updated': 'Обновлено',
    'data_updated': 'Данные обновлены',
    'failed_to_load_data': 'Ошибка загрузки данных',
    'from_date': 'Дата от',
    'to_date': 'Дата до',
    'expeditor': 'Экспедитор',
    'all': 'Все',
    'min_checks': 'Мин. чеки',
    'search': 'Поиск',
    'total_violations': 'Всего нарушений',
    'suspicious_patterns': 'Подозрительные случаи',
    'unique_expeditors': 'Экспедиторы',
    'total_checks': 'Всего чеков',
    'top_violators_by_risk': 'Топ нарушители по риску (ТОП 10)',
    'sorted_by_risk_level': 'Отсортированы по уровню риска',
    'unknown': 'Неизвестно',
    'checks': 'чеки',
    'violations': 'нарушения',
    'suspicious': 'подозрительный',
    'critical': 'критический',
    'view': 'Просмотр',
    'daily_violations': 'Ежедневные нарушения',
    'grouped_by_date': 'Нарушения, сгруппированные по дате',
    'no_data_found': 'Данные не найдены',
    'violations_count': 'нарушение',
    'checks_count': 'чек',
    'location_clusters_next_version': 'Кластеры местоположений будут добавлены в следующей версии',
    'no_checks_found_for_this_day': 'Чеки для этого дня не найдены',
    'checks_for_this_day': 'Чеки за этот день',
    'violations_short': 'нарушение',
    'clear_selection': 'Очистить выбор - Общая статистика',
    'colors_legend': 'Цвета:',
    'violations_explanation': 'Что считается нарушением:',
    'suspicious_explanation': 'Как определяются подозрительные чеки:',
    'gps_coordinates_wrong': 'GPS координаты неверные или отсутствуют',
    'expeditor_wrong_location': 'Во время чека экспедитор был в другом месте',
    'meeting_time_mismatch': 'Во время встречи с клиентом экспедитора там не было',
    'gps_signal_lost': 'GPS сигнал потерян или слабый',
    'route_deviation': 'Экспедитор отклонился от маршрута',
    'moving_during_check': 'Экспедитор двигался во время чека',
    'same_location_multiple_checks': 'Множественные чеки в одном месте',
    'multiple_locations_simultaneously': 'Экспедитор одновременно в нескольких местах',
    'frequent_gps_disconnection': 'Частые потери GPS сигнала',
    'constant_route_deviation': 'Постоянные отклонения от маршрута',
    'unusual_check_patterns': 'Необычные паттерны времени чеков',
    'too_many_or_few_checks': 'Слишком много или мало чеков за день',
    'gps_coordinates_stuck': 'GPS координаты застряли в одном месте',
    // User Guide Page
    'user_guide_title': 'Руководство пользователя',
    'user_guide_subtitle': 'Узнайте, как использовать систему Expeditor Tracker',
    'basic_functions': 'Основные функции',
    'filtering_and_search': 'Фильтрация и поиск',
    'statistics_and_analytics': 'Статистика и аналитика',
    'what_is_project': 'Что такое проект?',
    'map_tracking': 'Отслеживание на карте',
    'statistics_and_analysis': 'Статистика и анализ',
    'advanced_filtering': 'Расширенная фильтрация',
    'real_time_updates': 'Обновления в реальном времени',
    'map_section': 'Карта (Map)',
    'expeditors_list': 'Список экспедиторов',
    'checks_list': 'Список чеков',
    'statistics_panel': 'Панель статистики',
    'green_successful': 'Зеленый = Успешно',
    'red_problem': 'Красный = Проблема',
    'yellow_pending': 'Желтый = Ожидание',
    'what_to_do': 'Что нужно сделать:',
    'date_range_filter': 'Диапазон дат',
    'project_filter': 'Проект (Project)',
    'warehouse_filter': 'Склад (Sklad)',
    'city_filter': 'Город (City)',
    'status_filter': 'Статус',
    'search_filter': 'Поиск',
    'how_to_use': 'Как использовать:',
    'main_statistics': 'Основная статистика',
    'enhanced_analytics': 'Расширенная аналитика',
    'violation_analytics_title': 'Аналитика нарушений',
    'check_details_title': 'Подробная информация о чеке',
    'update_data_title': 'Обновление данных',
    'mobile_usage': 'Использование на мобильных устройствах',
    'telegram_webapp': 'Telegram WebApp',
    'mobile_browser': 'Мобильный браузер',
    'faq_title': 'Часто задаваемые вопросы',
    'tips_title': 'Советы по использованию',
    'back_to_home': 'Вернуться на главную',
    'check_id': 'ID чека',
    'client_name_address': 'Имя и адрес клиента',
    'delivery_time': 'Время доставки',
    'total_amount': 'Общая сумма',
    'payment_methods_detail': 'Способы оплаты (Наличные, UzCard, Humo, Click)',
    'gps_coordinates': 'GPS координаты',
    'what_is_check': 'В: Что такое чек?',
    'check_answer': 'О: Чек - это доставка (delivery). Каждый заказ считается одним чеком.',
    'what_is_expeditor': 'В: Что такое экспедитор?',
    'expeditor_answer': 'О: Экспедитор - это сотрудник доставки. Они доставляют заказы клиентам.',
    'map_no_points': 'В: Точки на карте не отображаются?',
    'map_no_points_answer': 'О: Проверьте фильтры. Проверьте, выбран ли экспедитор. Проверьте диапазон дат.',
    'data_not_updating': 'В: Данные не обновляются?',
    'data_not_updating_answer': 'О: Нажмите кнопку "Refresh". Или нажмите кнопку "Update Data". Подождите несколько секунд.',
    'stats_not_showing': 'В: Статистика не отображается?',
    'stats_not_showing_answer': 'О: Нажмите кнопку "Statistics". Или откройте панель статистики. Проверьте фильтры.',
    'save_filters': 'Сохраните фильтры',
    'save_filters_desc': 'Заполните фильтры. Система автоматически сохранит. При следующем входе автоматически загрузится.',
    'select_expeditor': 'Выберите экспедитора',
    'select_expeditor_desc': 'Нажмите на экспедитора. Будут показаны только его чеки. На карте будут показаны только его чеки.',
    'use_map': 'Используйте карту',
    'use_map_desc': 'Нажмите на маркер. Просмотрите подробную информацию. Перемещайтесь по карте.',
    'use_statistics': 'Используйте статистику',
    'use_statistics_desc': 'Откройте панель статистики. Анализируйте данные. Создавайте отчеты.',
    'filter_description': 'Нажмите кнопку фильтрации и используйте следующие фильтры:',
    'date_range_desc': '"From" (от) и "To" (до) - выберите даты начала и окончания. Можно выбрать из календаря.',
    'project_filter_desc': 'Выберите проект из выпадающего списка или выберите "All" (Все).',
    'warehouse_filter_desc': 'Выберите склад из выпадающего списка или выберите "All".',
    'city_filter_desc': 'Выберите город из выпадающего списка или выберите "All".',
    'status_filter_desc': 'Delivered (Доставлено), Failed (Неудачно), Pending (Ожидание) или выберите "All".',
    'search_filter_desc': 'Введите ID чека или имя клиента. Автоматически выполнится поиск.',
    'how_to_use_filters': 'Заполните фильтры → Нажмите кнопку "Apply" (Применить) → Результаты обновятся. Чтобы очистить фильтры, нажмите кнопку "Clear" (Очистить).',
    'map_description': 'На главной странице в центре отображается большая карта. На карте цветные точки (маркеры) - это чеки (доставки).',
    'map_what_to_do': 'Нажмите на маркер - отобразится подробная информация о чеке. Перемещайте карту (увеличение/уменьшение).',
    'expeditors_list_desc': 'Отображается список всех экспедиторов. Рядом с каждым экспедитором:',
    'expeditors_list_items': 'Имя, Количество чеков сегодня, Общее количество чеков, Фото (если есть)',
    'expeditors_what_to_do': 'Нажмите на экспедитора - отобразятся его чеки. В поле поиска введите имя для поиска.',
    'checks_list_desc': 'Отображаются все чеки выбранного экспедитора. В каждом чеке:',
    'checks_list_items': 'ID чека (номер), Имя клиента, Адрес, Время, Сумма, Статус (успешно/неудачно)',
    'checks_what_to_do': 'Нажмите на чек - откроется подробная информация. В поле поиска введите ID чека для поиска.',
    'statistics_panel_desc': 'На панели статистики отображается следующая информация:',
    'statistics_panel_items': 'Общее количество чеков, Общая сумма, Распределение по способам оплаты (Наличные, UzCard, Humo, Click), Уровень успеха (%)',
    'statistics_what_to_do': 'Нажмите кнопку "Statistics" (или откроется автоматически). Просмотрите и проанализируйте данные.',
    'check_details_desc': 'При нажатии на чек открывается модальное окно и отображается следующая информация:',
    'check_details_what_to_do': 'Просмотрите информацию → Нажмите кнопку "Close" (Закрыть). Или нажмите кнопку "Show on Map" для отображения на карте.',
    'update_data_desc': 'Для обновления данных:',
    'update_data_steps': '1. Нажмите кнопку "Refresh" (🔄) выше\n2. Или нажмите кнопку "Update Data"\n3. Отобразится индикатор прогресса\n4. Данные обновятся',
    'update_data_note': 'Обновление может занять несколько секунд. При больших данных может потребоваться больше времени.',
    'telegram_webapp_desc': 'Вход через Telegram бота. Или откройте в браузере. Интерфейс адаптирован для мобильных устройств.',
    'mobile_browser_desc': 'Войдите на сайт. Интерфейс автоматически адаптируется. Все функции работают.',
    'main_statistics_desc': 'На главной странице есть панель статистики. Или нажмите кнопку "Statistics".',
    'main_statistics_items': 'Общее количество чеков, Общая сумма, Уровень успеха (%), Распределение по способам оплаты, Лучшие экспедиторы, Лучшие проекты',
    'enhanced_analytics_desc': 'Нажмите кнопку "Analytics" выше или выберите "Enhanced Analytics".',
    'enhanced_analytics_items': 'Графики и диаграммы, Тренды, Анализ, Возможность экспорта',
    'violation_analytics_desc': 'Нажмите кнопку "Violation Analytics".',
    'violation_analytics_items': 'Проблемные чеки, Нарушения в одном месте, Статистика нарушений, Анализ',
  },
  en: {
    // Main page
    'expeditor_tracker': 'Expeditor Tracker',
    'update_data': 'Update Data',
    'last_update': 'Last Update',
    'date_range': 'Date Range',
    'today': 'Today',
    'selected': 'Selected',
    'filter': 'Filter',
    'search_expeditors': 'Search expeditors...',
    'no_expeditors_found': 'No expeditors found',
    'try_changing_filter': 'Try changing the filter',
    'checks_count': 'Checks',
    'uzs': 'UZS',
    'filial': 'Branch',
    'phone': 'Phone',
    'transport': 'Transport',
    'status': 'Status',
    'project': 'Project',
    'warehouse': 'Warehouse',
    'city': 'City',
    'all_projects': 'All Projects',
    'all_warehouses': 'All Warehouses',
    'all_cities': 'All Cities',
    'all_statuses': 'All Statuses',
    'clear_all_filters': 'Clear All Filters',
    'active_filters': 'Active Filters',
    'daily_routes': 'Daily Routes',
    'statistics': 'Statistics',
    'total_checks': 'Total Checks',
    'total_amount': 'Total Amount',
    'unique_expeditors': 'Expeditors',
    'average_checks': 'Average Checks',
    'show_stats': 'Show Statistics',
    'hide_stats': 'Hide Statistics',
    'language': 'Language',
    'select_expeditor_to_view_checks': 'Select an expeditor to view checks',
    'loading_checks': 'Loading checks...',
    'no_checks_found': 'No checks found',
    'try_adjusting_filters': 'Try adjusting the date range or filters',
    'loading_expeditors': 'Loading expeditors...',
    'success_rate': 'Success Rate',
    'payment_methods': 'Payment Methods',
    'cash': 'Cash',
    'uzcard': 'UzCard',
    'humo': 'Humo',
    'click': 'Click',
    'enhanced_analytics_dashboard': 'Enhanced Analytics Dashboard',
    'main_dashboard': 'Main Dashboard',
    'telegram_contact_dev': 'Telegram (Contact Dev)',
    'user_analytics': 'User Analytics',
    'sort_by': 'Sort by',
    'sort_name': 'Name',
    'sort_phone': 'Phone',
    'sort_transport': 'Transport',
    'sort_filial': 'Filial',
    'sort_checks_count': 'Checks Count',
    'sort_order': 'Order',
    'sort_ascending': 'Ascending (A-Z)',
    'sort_descending': 'Descending (Z-A)',
    'analytics_violations': 'Analytics & Violations',
    'enhanced_analytics': 'Enhanced Analytics',
    'violation_analytics': 'Violation Analytics',
    'same_location_violations': 'Same Location Violations',
    'buzilishlar_nazorati': 'Violations Control',
    'tasks_management': 'Tasks Management',
    'user_analytics': 'User Analytics',
    'yandex_tokens': 'Yandex Tokens',
    'check_pattern_analysis': 'Check pattern analysis - Time windows and geographic clusters',
    'logout': 'Logout',
    'real_time_analysis_fraud_detection': 'Real-time analysis and fraud detection',
    'comprehensive_statistics_insights': 'Comprehensive statistics and insights for expeditor performance',
    'export_all': 'Export All',
    'refresh': 'Refresh',
    'advanced_filters': 'Advanced Filters',
    'active': 'active',
    'visible': 'visible',
    'delivered': 'Delivered',
    'failed': 'Failed',
    'pending': 'Pending',
    'all_expeditor_checks': 'All expeditor checks',
    'successfully_delivered': 'Successfully delivered',
    'failed_deliveries': 'Failed deliveries',
    'awaiting_delivery': 'Awaiting delivery',
    'total_check_value': 'Total check value',
    'average_check': 'Average Check',
    'per_check_average': 'Per check average',
    'delivery_success_rate': 'Delivery success rate',
    'todays_checks': 'Today\'s Checks',
    'top_expeditors': 'Top Expeditors',
    'top_projects': 'Top Projects',
    'top_cities': 'Top Cities',
    'total_sum_uzs': 'Total Sum (UZS)',
    'average_check_sum_uzs': 'Average Check Sum (UZS)',
    'success_rate_percent': 'Success Rate (%)',
    'export': 'Export',
    'daily_check_distribution': 'Daily Check Distribution',
    'top_expeditors_by_check_count': 'Top Expeditors by Check Count',
    'top_projects_by_check_count': 'Top Projects by Check Count',
    'top_cities_by_check_count': 'Top Cities by Check Count',
    'chart_visibility_settings': 'Chart Visibility Settings',
    'dailyStats': 'Daily Stats',
    'hourlyStats': 'Hourly Stats',
    'topExpeditors': 'Top Expeditors',
    'topProjects': 'Top Projects',
    'topCities': 'Top Cities',
    'paymentMethods': 'Payment Methods',
    'loading_enhanced_statistics_page': 'Loading enhanced statistics page...',
    'filters': 'Filters',
    'date_from': 'Date From',
    'date_to': 'Date To',
    'expeditor': 'Expeditor',
    'min_checks': 'Min Checks',
    'max_checks': 'Max Checks',
    'radius_meters': 'Radius (meters)',
    'select_radius': 'Select radius',
    'window_duration_min': 'Window Duration (min)',
    'select_duration': 'Select duration',
    'clear_filters': 'Clear Filters',
    'analytics_summary': 'Analytics Summary',
    'time_window': 'Time Window',
    'most_active': 'Most Active',
    'total_records': 'Total Records',
    'avg_checks_window': 'Avg Checks/Window',
    'analytics_data': 'Analytics Data',
    'per_page': 'Per page',
    'showing': 'Showing',
    'to': 'to',
    'of': 'of',
    'records': 'records',
    'view_details': 'View Details',
    'violation_details': 'Violation Details',
    'check_details': 'Check Details',
    'location': 'Location',
    'most_active_expeditor': 'Most Active Expeditor',
    'area': 'Area',
    'actions': 'Actions',
    'date_time': 'Date & Time',
    'previous': 'Previous',
    'next': 'Next',
    'page': 'Page',
    'success': 'Success',
    'error': 'Error',
    'data_refreshed_successfully': 'Data refreshed successfully',
    'failed_to_load_analytics_data': 'Failed to load analytics data',
    'report_exported_successfully': 'Report exported successfully',
    'failed_to_load_violation_checks': 'Failed to load violation checks',
    'loading_analytics_dashboard': 'Loading analytics dashboard...',
    'no_analytics_data_available': 'No analytics data available',
    'retry': 'Retry',
    'violation_analytics': 'Violation Analytics',
    'real_time_pattern_detection_analysis': 'Real-time pattern detection and analysis',
    'apply_filters': 'Apply Filters',
    'clear_all': 'Clear All',
    'total_violations': 'Total Violations',
    'checks_involved': 'Checks Involved',
    'expeditors_count': 'Expeditors',
    'avg_radius': 'Avg Radius',
    'top_violators': 'Top Violators',
    'violators': 'Violators',
    'violation_checks': 'Violation Checks',
    'geography': 'Geography',
    'map': 'Map',
    'time': 'Time',
    'severity': 'Severity',
    'level': 'Level',
    'trends': 'Trends',
    'trend': 'Trend',
    'min_radius': 'Min Radius (m)',
    'max_radius': 'Max Radius (m)',
    'violation_checks_data': 'Violation Checks Data',
    'click_to_load_violation_checks': 'Click to load violation checks',
    'client': 'Client',
    'total_sum': 'Total Sum',
    'top_10_violators': 'Top 10 Violators',
    'most_frequent_violation_patterns': 'Most frequent violation patterns',
    'avg': 'Avg',
    'violations_count': 'violations',
    'click_for_details': 'Click for details',
    'performance_metrics': 'Performance Metrics',
    'detailed_expeditor_statistics': 'Detailed expeditor statistics',
    'avg_v': 'Avg/V',
    'geographic_hotspots': 'Geographic Hotspots',
    'areas_with_highest_violation_density': 'Areas with highest violation density',
    'time_analysis': 'Time Analysis',
    'violation_patterns_by_time_periods': 'Violation patterns by time periods',
    'daily_distribution': 'Daily Distribution',
    'violations_by_day_of_week': 'Violations by day of week',
    'hourly_pattern': 'Hourly Pattern',
    'peak_violation_hours': 'Peak violation hours',
    'severity_levels': 'Severity Levels',
    'categorized_by_violation_radius': 'Categorized by violation radius',
    'critical': 'Critical',
    'warning': 'Warning',
    'minor': 'Minor',
    'meters': 'meters',
    'daily_trend_analysis': 'Daily Trend Analysis',
    'violation_trends_over_time': 'Violation trends over time',
    'filters': 'Filters',
    'refresh': 'Refresh',
    'updated': 'Updated',
    'data_updated': 'Data updated',
    'failed_to_load_data': 'Failed to load data',
    'from_date': 'From Date',
    'to_date': 'To Date',
    'expeditor': 'Expeditor',
    'all': 'All',
    'min_checks': 'Min Checks',
    'search': 'Search',
    'total_violations': 'Total Violations',
    'suspicious_patterns': 'Suspicious Patterns',
    'unique_expeditors': 'Expeditors',
    'total_checks': 'Total Checks',
    'top_violators_by_risk': 'Top Violators by Risk (TOP 10)',
    'sorted_by_risk_level': 'Sorted by risk level',
    'unknown': 'Unknown',
    'checks': 'checks',
    'violations': 'violations',
    'suspicious': 'suspicious',
    'critical': 'critical',
    'view': 'View',
    'daily_violations': 'Daily Violations',
    'grouped_by_date': 'Violations grouped by date',
    'no_data_found': 'No data found',
    'violations_count': 'violations',
    'checks_count': 'checks',
    'location_clusters_next_version': 'Location clusters will be added in the next version',
    'buzilishlar_nazorati': 'Violations Control',
    'real_time_analysis_fraud_detection': 'Real-time analysis and fraud detection',
    'filters': 'Filters',
    'refresh': 'Refresh',
    'updated': 'Updated',
    'data_updated': 'Data updated',
    'failed_to_load_data': 'Failed to load data',
    'from_date': 'From Date',
    'to_date': 'To Date',
    'expeditor': 'Expeditor',
    'all': 'All',
    'min_checks': 'Min Checks',
    'search': 'Search',
    'total_violations': 'Total Violations',
    'suspicious_patterns': 'Suspicious Patterns',
    'unique_expeditors': 'Expeditors',
    'total_checks': 'Total Checks',
    'top_violators_by_risk': 'Top Violators by Risk (TOP 10)',
    'sorted_by_risk_level': 'Sorted by risk level',
    'unknown': 'Unknown',
    'checks': 'checks',
    'violations': 'violations',
    'suspicious': 'suspicious',
    'critical': 'critical',
    'view': 'View',
    'daily_violations': 'Daily Violations',
    'grouped_by_date': 'Violations grouped by date',
    'no_data_found': 'No data found',
    'violations_count': 'violations',
    'checks_count': 'checks',
    'location_clusters_next_version': 'Location clusters will be added in the next version',
    'no_checks_found_for_this_day': 'No checks found for this day',
    'checks_for_this_day': 'Checks for this day',
    'violations_short': 'violations',
    'clear_selection': 'Clear selection - Overall statistics',
    'colors_legend': 'Colors:',
    'violations_explanation': 'What counts as violations:',
    'suspicious_explanation': 'How suspicious checks are detected:',
    'gps_coordinates_wrong': 'GPS coordinates are wrong or missing',
    'expeditor_wrong_location': 'Expeditor was in wrong location during check',
    'meeting_time_mismatch': 'Expeditor was not there during client meeting',
    'gps_signal_lost': 'GPS signal lost or weak',
    'route_deviation': 'Expeditor deviated from route',
    'moving_during_check': 'Expeditor was moving during check',
    'same_location_multiple_checks': 'Multiple checks at same location',
    'multiple_locations_simultaneously': 'Expeditor in multiple places simultaneously',
    'frequent_gps_disconnection': 'Frequent GPS signal disconnections',
    'constant_route_deviation': 'Constant deviations from route',
    'unusual_check_patterns': 'Unusual check time patterns',
    'too_many_or_few_checks': 'Too many or too few checks per day',
    'gps_coordinates_stuck': 'GPS coordinates stuck in same place',
    // User Guide Page
    'user_guide_title': 'User Guide',
    'user_guide_subtitle': 'Learn how to use the Expeditor Tracker system',
    'basic_functions': 'Basic Functions',
    'filtering_and_search': 'Filtering and Search',
    'statistics_and_analytics': 'Statistics and Analytics',
    'what_is_project': 'What is the Project?',
    'map_tracking': 'Map Tracking',
    'statistics_and_analysis': 'Statistics and Analysis',
    'advanced_filtering': 'Advanced Filtering',
    'real_time_updates': 'Real-time Updates',
    'map_section': 'Map',
    'expeditors_list': 'Expeditors List',
    'checks_list': 'Checks List',
    'statistics_panel': 'Statistics Panel',
    'green_successful': 'Green = Successful',
    'red_problem': 'Red = Problem',
    'yellow_pending': 'Yellow = Pending',
    'what_to_do': 'What to do:',
    'date_range_filter': 'Date Range',
    'project_filter': 'Project',
    'warehouse_filter': 'Warehouse (Sklad)',
    'city_filter': 'City',
    'status_filter': 'Status',
    'search_filter': 'Search',
    'how_to_use': 'How to use:',
    'main_statistics': 'Main Statistics',
    'enhanced_analytics': 'Enhanced Analytics',
    'violation_analytics_title': 'Violation Analytics',
    'check_details_title': 'Check Details',
    'update_data_title': 'Update Data',
    'mobile_usage': 'Mobile Usage',
    'telegram_webapp': 'Telegram WebApp',
    'mobile_browser': 'Mobile Browser',
    'faq_title': 'Frequently Asked Questions',
    'tips_title': 'Usage Tips',
    'back_to_home': 'Back to Home',
    'check_id': 'Check ID',
    'client_name_address': 'Client name and address',
    'delivery_time': 'Delivery time',
    'total_amount': 'Total amount',
    'payment_methods_detail': 'Payment methods (Cash, UzCard, Humo, Click)',
    'gps_coordinates': 'GPS coordinates',
    'what_is_check': 'Q: What is a check?',
    'check_answer': 'A: Check is a delivery. Each order is considered one check.',
    'what_is_expeditor': 'Q: What is an expeditor?',
    'expeditor_answer': 'A: Expeditor is a delivery employee. They deliver orders to customers.',
    'map_no_points': 'Q: Points not showing on map?',
    'map_no_points_answer': 'A: Check filters. Check if expeditor is selected. Check date range.',
    'data_not_updating': 'Q: Data not updating?',
    'data_not_updating_answer': 'A: Click "Refresh" button. Or click "Update Data" button. Wait a few seconds.',
    'stats_not_showing': 'Q: Statistics not showing?',
    'stats_not_showing_answer': 'A: Click "Statistics" button. Or open statistics panel. Check filters.',
    'save_filters': 'Save filters',
    'save_filters_desc': 'Fill in filters. System automatically saves. Next time will automatically load.',
    'select_expeditor': 'Select expeditor',
    'select_expeditor_desc': 'Click on expeditor. Only his checks will be shown. On map only his checks will be displayed.',
    'use_map': 'Use map',
    'use_map_desc': 'Click on marker. View detailed information. Move around the map.',
    'use_statistics': 'Use statistics',
    'use_statistics_desc': 'Open statistics panel. Analyze data. Create reports.',
    'filter_description': 'Click filter button and use the following filters:',
    'date_range_desc': '"From" and "To" - select start and end dates. Can select from calendar.',
    'project_filter_desc': 'Select project from dropdown or select "All".',
    'warehouse_filter_desc': 'Select warehouse from dropdown or select "All".',
    'city_filter_desc': 'Select city from dropdown or select "All".',
    'status_filter_desc': 'Delivered, Failed, Pending or select "All".',
    'search_filter_desc': 'Type check ID or client name. Will automatically search.',
    'how_to_use_filters': 'Fill in filters → Click "Apply" button → Results will update. To clear filters, click "Clear" button.',
    'map_description': 'On main page center shows large map. On map colored dots (markers) - these are checks (deliveries).',
    'map_what_to_do': 'Click on marker - detailed check information will appear. Move map (zoom in/out).',
    'expeditors_list_desc': 'List of all expeditors is shown. Next to each expeditor:',
    'expeditors_list_items': 'Name, Today\'s checks count, Total checks count, Photo (if available)',
    'expeditors_what_to_do': 'Click on expeditor - his checks will be shown. In search field type name to search.',
    'checks_list_desc': 'All checks of selected expeditor are shown. In each check:',
    'checks_list_items': 'Check ID (number), Client name, Address, Time, Amount, Status (successful/failed)',
    'checks_what_to_do': 'Click on check - detailed information will open. In search field type check ID to search.',
    'statistics_panel_desc': 'Statistics panel shows the following information:',
    'statistics_panel_items': 'Total checks count, Total amount, Payment methods distribution (Cash, UzCard, Humo, Click), Success rate (%)',
    'statistics_what_to_do': 'Click "Statistics" button (or will open automatically). View and analyze data.',
    'check_details_desc': 'When clicking on check, modal window opens and shows the following information:',
    'check_details_what_to_do': 'View information → Click "Close" button. Or click "Show on Map" button to show on map.',
    'update_data_desc': 'To update data:',
    'update_data_steps': '1. Click "Refresh" (🔄) button above\n2. Or click "Update Data" button\n3. Progress bar will appear\n4. Data will update',
    'update_data_note': 'Update may take a few seconds. With large data it may take longer.',
    'telegram_webapp_desc': 'Login via Telegram bot. Or open in browser. Interface is adapted for mobile devices.',
    'mobile_browser_desc': 'Login to site. Interface automatically adapts. All functions work.',
    'main_statistics_desc': 'Main page has statistics panel. Or click "Statistics" button.',
    'main_statistics_items': 'Total checks count, Total amount, Success rate (%), Payment methods distribution, Top expeditors, Top projects',
    'enhanced_analytics_desc': 'Click "Analytics" button above or select "Enhanced Analytics".',
    'enhanced_analytics_items': 'Charts and graphs, Trends, Analysis, Export capability',
    'violation_analytics_desc': 'Click "Violation Analytics" button.',
    'violation_analytics_items': 'Problem checks, Same location violations, Violations statistics, Analysis',
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('uz')

  // Load saved language from localStorage
  useEffect(() => {
    if (typeof window === 'undefined') return
    try {
      const savedLanguage = localStorage.getItem('user_language') as Language
      if (savedLanguage && ['uz', 'ru', 'en'].includes(savedLanguage)) {
        setLanguage(savedLanguage)
      }
    } catch (error) {
      console.error('Error loading saved language:', error)
    }
  }, [])

  // Save language to localStorage
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    if (typeof window !== 'undefined') {
      try {
        localStorage.setItem('user_language', lang)
      } catch (error) {
        console.error('Error saving language:', error)
      }
    }
  }

  // Translation function
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
