"use client"

import { createContext, useContext, useEffect, useState, ReactNode } from "react"

export type Language = 'uz' | 'ru' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation keys
const translations = {
  uz: {
    // Main page
    'expeditor_tracker': 'Ekspeditor Kuzatuvchi',
    'update_data': 'Ma\'lumotlarni yangilash',
    'last_update': 'Oxirgi yangilanish',
    'date_range': 'Sana oralig\'i',
    'today': 'Bugun',
    'selected': 'Tanlangan',
    'filter': 'Filter',
    'search_expeditors': 'Ekspeditorlarni qidirish...',
    'no_expeditors_found': 'Ekspeditorlar topilmadi',
    'try_changing_filter': 'Filterni o\'zgartirib ko\'ring',
    'checks_count': 'Cheklar',
    'uzs': 'UZS',
    'filial': 'Filial',
    'phone': 'Telefon',
    'transport': 'Transport',
    'status': 'Holat',
    'project': 'Loyiha',
    'warehouse': 'Ombor',
    'city': 'Shahar',
    'all_projects': 'Barcha loyihalar',
    'all_warehouses': 'Barcha omborlar',
    'all_cities': 'Barcha shaharlar',
    'all_statuses': 'Barcha holatlar',
    'clear_all_filters': 'Barcha filterlarni tozalash',
    'active_filters': 'Faol filterlar',
    'daily_routes': 'Kunlik yo\'nalishlar',
    'statistics': 'Statistika',
    'total_checks': 'Jami cheklar',
    'total_amount': 'Jami summa',
    'unique_expeditors': 'Ekspeditorlar',
    'average_checks': 'O\'rtacha cheklar',
    'show_stats': 'Statistikani ko\'rsatish',
    'hide_stats': 'Statistikani yashirish',
    'language': 'Til',
    'select_expeditor_to_view_checks': 'Cheklarni ko\'rish uchun ekspeditor tanlang',
    'loading_checks': 'Cheklar yuklanmoqda...',
    'no_checks_found': 'Cheklar topilmadi',
    'try_adjusting_filters': 'Sana oralig\'i yoki filterlarni o\'zgartiring',
    'loading_expeditors': 'Ekspeditorlar yuklanmoqda...',
    'success_rate': 'Muvaffaqiyat darajasi',
    'payment_methods': 'To\'lov usullari',
    'cash': 'Naqd pul',
    'uzcard': 'UzCard',
    'humo': 'Humo',
    'click': 'Click',
    'enhanced_analytics_dashboard': 'Kengaytirilgan Analytics Dashboard',
    'main_dashboard': 'Asosiy Dashboard',
    'telegram_contact_dev': 'Telegram (Dev bilan aloqa)',
    'analytics_violations': 'Analytics va Buzilishlar',
    'enhanced_analytics': 'Kengaytirilgan Analytics',
    'violation_analytics': 'Buzilish Analytics',
    'same_location_violations': 'Bir xil joy buzilishlari',
    'buzilishlar_nazorati': 'Buzilishlar Nazorati',
    'tasks_management': 'Vazifalar boshqaruvi',
    'yandex_tokens': 'Yandex Tokens',
    'check_pattern_analysis': 'Check naqshlarini tahlil qilish - Vaqt oynalari va geografik klasterlar',
    'logout': 'Chiqish',
    'real_time_analysis_fraud_detection': 'Real vaqt tahlili va fraud aniqlash',
    'comprehensive_statistics_insights': 'Kengaytirilgan statistika va ekspeditor ishlashi uchun tahlil',
    'export_all': 'Hammasini eksport qilish',
    'refresh': 'Yangilash',
    'advanced_filters': 'Kengaytirilgan filterlar',
    'active': 'faol',
    'visible': 'ko\'rinadi',
    'delivered': 'Yetkazilgan',
    'failed': 'Muvaffaqiyatsiz',
    'pending': 'Kutilmoqda',
    'all_expeditor_checks': 'Barcha ekspeditor cheklari',
    'successfully_delivered': 'Muvaffaqiyatli yetkazilgan',
    'failed_deliveries': 'Muvaffaqiyatsiz yetkazishlar',
    'awaiting_delivery': 'Yetkazishni kutmoqda',
    'total_check_value': 'Jami check qiymati',
    'average_check': 'O\'rtacha check',
    'per_check_average': 'Har bir check uchun o\'rtacha',
    'delivery_success_rate': 'Yetkazish muvaffaqiyat darajasi',
    'todays_checks': 'Bugungi cheklar',
    'top_expeditors': 'Eng yaxshi ekspeditorlar',
    'top_projects': 'Eng yaxshi loyihalar',
    'top_cities': 'Eng yaxshi shaharlar',
    'total_sum_uzs': 'Jami summa (UZS)',
    'average_check_sum_uzs': 'O\'rtacha check summasi (UZS)',
    'success_rate_percent': 'Muvaffaqiyat darajasi (%)',
    'export': 'Eksport qilish',
    'daily_check_distribution': 'Kunlik check taqsimoti',
    'top_expeditors_by_check_count': 'Eng yaxshi ekspeditorlar (check soni bo\'yicha)',
    'top_projects_by_check_count': 'Eng yaxshi loyihalar (check soni bo\'yicha)',
    'top_cities_by_check_count': 'Eng yaxshi shaharlar (check soni bo\'yicha)',
    'chart_visibility_settings': 'Chart ko\'rinish sozlamalari',
    'dailyStats': 'Kunlik statistika',
    'hourlyStats': 'Soatlik statistika',
    'topExpeditors': 'Eng yaxshi ekspeditorlar',
    'topProjects': 'Eng yaxshi loyihalar',
    'topCities': 'Eng yaxshi shaharlar',
    'paymentMethods': 'To\'lov usullari',
    'loading_enhanced_statistics_page': 'Kengaytirilgan statistika sahifasi yuklanmoqda...',
    'filters': 'Filterlar',
    'date_from': 'Boshlanish sanasi',
    'date_to': 'Tugash sanasi',
    'expeditor': 'Ekspeditor',
    'min_checks': 'Minimal cheklar',
    'max_checks': 'Maksimal cheklar',
    'radius_meters': 'Radius (metr)',
    'select_radius': 'Radius tanlang',
    'window_duration_min': 'Oyna davomiyligi (min)',
    'select_duration': 'Davomiylikni tanlang',
    'clear_filters': 'Filterlarni tozalash',
    'analytics_summary': 'Analytics xulosa',
    'time_window': 'Vaqt oynasi',
    'most_active': 'Eng faol',
    'total_records': 'Jami yozuvlar',
    'avg_checks_window': 'O\'rtacha cheklar/oyna',
    'analytics_data': 'Analytics ma\'lumotlari',
    'per_page': 'Har sahifada',
    'showing': 'Ko\'rsatilmoqda',
    'to': 'dan',
    'of': 'dan',
    'records': 'yozuvlar',
    'view_details': 'Tafsilotlarni ko\'rish',
    'violation_details': 'Buzilish tafsilotlari',
    'check_details': 'Check tafsilotlari',
    'location': 'Joylashuv',
    'most_active_expeditor': 'Eng faol ekspeditor',
    'area': 'Hudud',
    'actions': 'Amallar',
    'date_time': 'Sana va vaqt',
    'previous': 'Oldingi',
    'next': 'Keyingi',
    'page': 'Sahifa',
    'success': 'Muvaffaqiyat',
    'error': 'Xatolik',
    'data_refreshed_successfully': 'Ma\'lumotlar muvaffaqiyatli yangilandi',
    'failed_to_load_analytics_data': 'Analytics ma\'lumotlarini yuklashda xatolik',
    'report_exported_successfully': 'Hisobot muvaffaqiyatli eksport qilindi',
    'failed_to_load_violation_checks': 'Buzilish cheklarini yuklashda xatolik',
    'loading_analytics_dashboard': 'Analytics dashboard yuklanmoqda...',
    'no_analytics_data_available': 'Analytics ma\'lumotlari mavjud emas',
    'retry': 'Qayta urinish',
    'violation_analytics': 'Buzilish Analytics',
    'real_time_pattern_detection_analysis': 'Real vaqt naqsh aniqlash va tahlil',
    'apply_filters': 'Filterlarni qo\'llash',
    'clear_all': 'Barchasini tozalash',
    'total_violations': 'Jami buzilishlar',
    'checks_involved': 'Jami cheklar',
    'expeditors_count': 'Ekspeditorlar',
    'avg_radius': 'O\'rtacha radius',
    'top_violators': 'Eng ko\'p buzilish qiluvchilar',
    'violators': 'Buzilish qiluvchilar',
    'violation_checks': 'Buzilish cheklari',
    'geography': 'Geografiya',
    'map': 'Xarita',
    'time': 'Vaqt',
    'severity': 'Jiddiylik',
    'level': 'Daraja',
    'trends': 'Trendlar',
    'trend': 'Trend',
    'min_radius': 'Minimal radius (m)',
    'max_radius': 'Maksimal radius (m)',
    'violation_checks_data': 'Buzilish cheklari ma\'lumotlari',
    'click_to_load_violation_checks': 'Buzilish cheklarini yuklash uchun bosing',
    'client': 'Mijoz',
    'total_sum': 'Jami summa',
    'top_10_violators': 'Top 10 buzilish qiluvchilar',
    'most_frequent_violation_patterns': 'Eng tez-tez uchraydigan buzilish naqshlari',
    'avg': 'O\'rtacha',
    'violations_count': 'buzilishlar',
    'click_for_details': 'Tafsilotlar uchun bosing',
    'performance_metrics': 'Ishlash ko\'rsatkichlari',
    'detailed_expeditor_statistics': 'Batafsil ekspeditor statistikasi',
    'avg_v': 'O\'rtacha/B',
    'geographic_hotspots': 'Geografik issiq nuqtalar',
    'areas_with_highest_violation_density': 'Eng yuqori buzilish zichligi bo\'lgan hududlar',
    'time_analysis': 'Vaqt tahlili',
    'violation_patterns_by_time_periods': 'Vaqt davrlari bo\'yicha buzilish naqshlari',
    'daily_distribution': 'Kunlik taqsimot',
    'violations_by_day_of_week': 'Hafta kunlari bo\'yicha buzilishlar',
    'hourly_pattern': 'Soatlik naqsh',
    'peak_violation_hours': 'Eng ko\'p buzilish soatlari',
    'severity_levels': 'Jiddiylik darajalari',
    'categorized_by_violation_radius': 'Buzilish radiusi bo\'yicha tasniflash',
    'critical': 'Jiddiy',
    'warning': 'Ogohlantirish',
    'minor': 'Kichik',
    'meters': 'metr',
    'daily_trend_analysis': 'Kunlik trend tahlili',
    'violation_trends_over_time': 'Vaqt o\'tishi bilan buzilish trendlari',
    'filters': 'Filterlar',
    'refresh': 'Yangilash',
    'updated': 'Yangilandi',
    'data_updated': 'Ma\'lumotlar yangilandi',
    'failed_to_load_data': 'Ma\'lumotlarni yuklashda xatolik',
    'from_date': 'Sanadan',
    'to_date': 'Sanagacha',
    'expeditor': 'Ekspiditor',
    'all': 'Barchasi',
    'min_checks': 'Min Cheklar',
    'search': 'Qidirish',
    'total_violations': 'Jami Buzilishlar',
    'suspicious_patterns': 'Shubhali Holatlar',
    'unique_expeditors': 'Ekspiditorlar',
    'total_checks': 'Jami Cheklar',
    'top_violators_by_risk': 'Eng Ko\'p Buzilish Qilgan Ekspiditorlar (TOP 10)',
    'sorted_by_risk_level': 'Risk darajasi bo\'yicha tartiblangan',
    'unknown': 'Noma\'lum',
    'checks': 'chek',
    'violations': 'buzilish',
    'suspicious': 'shubhali',
    'critical': 'kritik',
    'view': 'Ko\'rish',
    'daily_violations': 'Kunlik Buzilishlar',
    'grouped_by_date': 'Sana bo\'yicha gruppalangan buzilishlar',
    'no_data_found': 'Ma\'lumot topilmadi',
    'violations_count': 'buzilish',
    'checks_count': 'chek',
    'location_clusters_next_version': 'Joylashuv klasterlari keyingi versiyada qo\'shiladi',
  },
  ru: {
    // Main page
    'expeditor_tracker': 'Трекер Экспедиторов',
    'update_data': 'Обновить данные',
    'last_update': 'Последнее обновление',
    'date_range': 'Диапазон дат',
    'today': 'Сегодня',
    'selected': 'Выбрано',
    'filter': 'Фильтр',
    'search_expeditors': 'Поиск экспедиторов...',
    'no_expeditors_found': 'Экспедиторы не найдены',
    'try_changing_filter': 'Попробуйте изменить фильтр',
    'checks_count': 'Чеки',
    'uzs': 'UZS',
    'filial': 'Филиал',
    'phone': 'Телефон',
    'transport': 'Транспорт',
    'status': 'Статус',
    'project': 'Проект',
    'warehouse': 'Склад',
    'city': 'Город',
    'all_projects': 'Все проекты',
    'all_warehouses': 'Все склады',
    'all_cities': 'Все города',
    'all_statuses': 'Все статусы',
    'clear_all_filters': 'Очистить все фильтры',
    'active_filters': 'Активные фильтры',
    'daily_routes': 'Ежедневные маршруты',
    'statistics': 'Статистика',
    'total_checks': 'Всего чеков',
    'total_amount': 'Общая сумма',
    'unique_expeditors': 'Экспедиторы',
    'average_checks': 'Средние чеки',
    'show_stats': 'Показать статистику',
    'hide_stats': 'Скрыть статистику',
    'language': 'Язык',
    'select_expeditor_to_view_checks': 'Выберите экспедитора для просмотра чеков',
    'loading_checks': 'Загрузка чеков...',
    'no_checks_found': 'Чеки не найдены',
    'try_adjusting_filters': 'Попробуйте изменить диапазон дат или фильтры',
    'loading_expeditors': 'Загрузка экспедиторов...',
    'success_rate': 'Уровень успеха',
    'payment_methods': 'Способы оплаты',
    'cash': 'Наличные',
    'uzcard': 'UzCard',
    'humo': 'Humo',
    'click': 'Click',
    'enhanced_analytics_dashboard': 'Расширенная аналитическая панель',
    'main_dashboard': 'Главная панель',
    'telegram_contact_dev': 'Telegram (Связаться с разработчиком)',
    'analytics_violations': 'Аналитика и нарушения',
    'enhanced_analytics': 'Расширенная аналитика',
    'violation_analytics': 'Аналитика нарушений',
    'same_location_violations': 'Нарушения в одном месте',
    'buzilishlar_nazorati': 'Контроль нарушений',
    'tasks_management': 'Управление задачами',
    'yandex_tokens': 'Yandex токены',
    'check_pattern_analysis': 'Анализ паттернов чеков - Временные окна и географические кластеры',
    'logout': 'Выйти',
    'real_time_analysis_fraud_detection': 'Анализ в реальном времени и обнаружение мошенничества',
    'comprehensive_statistics_insights': 'Комплексная статистика и аналитика производительности экспедиторов',
    'export_all': 'Экспорт всего',
    'refresh': 'Обновить',
    'advanced_filters': 'Расширенные фильтры',
    'active': 'активно',
    'visible': 'видимо',
    'delivered': 'Доставлено',
    'failed': 'Неудачно',
    'pending': 'В ожидании',
    'all_expeditor_checks': 'Все чеки экспедиторов',
    'successfully_delivered': 'Успешно доставлено',
    'failed_deliveries': 'Неудачные доставки',
    'awaiting_delivery': 'Ожидает доставки',
    'total_check_value': 'Общая стоимость чеков',
    'average_check': 'Средний чек',
    'per_check_average': 'Среднее за чек',
    'delivery_success_rate': 'Уровень успеха доставки',
    'todays_checks': 'Чеки сегодня',
    'top_expeditors': 'Топ экспедиторы',
    'top_projects': 'Топ проекты',
    'top_cities': 'Топ города',
    'total_sum_uzs': 'Общая сумма (UZS)',
    'average_check_sum_uzs': 'Средняя сумма чека (UZS)',
    'success_rate_percent': 'Уровень успеха (%)',
    'export': 'Экспорт',
    'daily_check_distribution': 'Ежедневное распределение чеков',
    'top_expeditors_by_check_count': 'Топ экспедиторы (по количеству чеков)',
    'top_projects_by_check_count': 'Топ проекты (по количеству чеков)',
    'top_cities_by_check_count': 'Топ города (по количеству чеков)',
    'chart_visibility_settings': 'Настройки видимости графиков',
    'dailyStats': 'Ежедневная статистика',
    'hourlyStats': 'Почасовая статистика',
    'topExpeditors': 'Топ экспедиторы',
    'topProjects': 'Топ проекты',
    'topCities': 'Топ города',
    'paymentMethods': 'Способы оплаты',
    'loading_enhanced_statistics_page': 'Загрузка расширенной страницы статистики...',
    'filters': 'Фильтры',
    'date_from': 'Дата от',
    'date_to': 'Дата до',
    'expeditor': 'Экспедитор',
    'min_checks': 'Мин. чеки',
    'max_checks': 'Макс. чеки',
    'radius_meters': 'Радиус (метры)',
    'select_radius': 'Выберите радиус',
    'window_duration_min': 'Длительность окна (мин)',
    'select_duration': 'Выберите длительность',
    'clear_filters': 'Очистить фильтры',
    'analytics_summary': 'Сводка аналитики',
    'time_window': 'Временное окно',
    'most_active': 'Самый активный',
    'total_records': 'Всего записей',
    'avg_checks_window': 'Среднее чеков/окно',
    'analytics_data': 'Данные аналитики',
    'per_page': 'На странице',
    'showing': 'Показано',
    'to': 'до',
    'of': 'из',
    'records': 'записей',
    'view_details': 'Просмотр',
    'violation_details': 'Детали нарушений',
    'check_details': 'Детали чеков',
    'location': 'Местоположение',
    'most_active_expeditor': 'Самый активный экспедитор',
    'area': 'Область',
    'actions': 'Действия',
    'date_time': 'Дата и время',
    'previous': 'Предыдущая',
    'next': 'Следующая',
    'page': 'Страница',
    'success': 'Успех',
    'error': 'Ошибка',
    'data_refreshed_successfully': 'Данные успешно обновлены',
    'failed_to_load_analytics_data': 'Ошибка загрузки данных аналитики',
    'report_exported_successfully': 'Отчет успешно экспортирован',
    'failed_to_load_violation_checks': 'Ошибка загрузки чеков нарушений',
    'loading_analytics_dashboard': 'Загрузка панели аналитики...',
    'no_analytics_data_available': 'Данные аналитики недоступны',
    'retry': 'Повторить',
    'violation_analytics': 'Аналитика нарушений',
    'real_time_pattern_detection_analysis': 'Обнаружение и анализ паттернов в реальном времени',
    'apply_filters': 'Применить фильтры',
    'clear_all': 'Очистить все',
    'total_violations': 'Всего нарушений',
    'checks_involved': 'Задействованные чеки',
    'expeditors_count': 'Экспедиторы',
    'avg_radius': 'Средний радиус',
    'top_violators': 'Топ нарушители',
    'violators': 'Нарушители',
    'violation_checks': 'Чеки нарушений',
    'geography': 'География',
    'map': 'Карта',
    'time': 'Время',
    'severity': 'Серьезность',
    'level': 'Уровень',
    'trends': 'Тренды',
    'trend': 'Тренд',
    'min_radius': 'Минимальный радиус (м)',
    'max_radius': 'Максимальный радиус (м)',
    'violation_checks_data': 'Данные чеков нарушений',
    'click_to_load_violation_checks': 'Нажмите для загрузки чеков нарушений',
    'client': 'Клиент',
    'total_sum': 'Общая сумма',
    'top_10_violators': 'Топ 10 нарушителей',
    'most_frequent_violation_patterns': 'Наиболее частые паттерны нарушений',
    'avg': 'Среднее',
    'violations_count': 'нарушения',
    'click_for_details': 'Нажмите для деталей',
    'performance_metrics': 'Метрики производительности',
    'detailed_expeditor_statistics': 'Подробная статистика экспедиторов',
    'avg_v': 'Среднее/Н',
    'geographic_hotspots': 'Географические горячие точки',
    'areas_with_highest_violation_density': 'Области с наибольшей плотностью нарушений',
    'time_analysis': 'Анализ времени',
    'violation_patterns_by_time_periods': 'Паттерны нарушений по временным периодам',
    'daily_distribution': 'Ежедневное распределение',
    'violations_by_day_of_week': 'Нарушения по дням недели',
    'hourly_pattern': 'Почасовой паттерн',
    'peak_violation_hours': 'Часы пиковых нарушений',
    'severity_levels': 'Уровни серьезности',
    'categorized_by_violation_radius': 'Категоризация по радиусу нарушения',
    'critical': 'Критический',
    'warning': 'Предупреждение',
    'minor': 'Незначительный',
    'meters': 'метры',
    'daily_trend_analysis': 'Анализ ежедневных трендов',
    'violation_trends_over_time': 'Тренды нарушений во времени',
    'filters': 'Фильтры',
    'refresh': 'Обновить',
    'updated': 'Обновлено',
    'data_updated': 'Данные обновлены',
    'failed_to_load_data': 'Ошибка загрузки данных',
    'from_date': 'С даты',
    'to_date': 'До даты',
    'expeditor': 'Экспедитор',
    'all': 'Все',
    'min_checks': 'Мин. чеки',
    'search': 'Поиск',
    'total_violations': 'Всего нарушений',
    'suspicious_patterns': 'Подозрительные случаи',
    'unique_expeditors': 'Экспедиторы',
    'total_checks': 'Всего чеков',
    'top_violators_by_risk': 'Топ нарушители по риску (ТОП 10)',
    'sorted_by_risk_level': 'Отсортированы по уровню риска',
    'unknown': 'Неизвестно',
    'checks': 'чек',
    'violations': 'нарушение',
    'suspicious': 'подозрительный',
    'critical': 'критический',
    'view': 'Просмотр',
    'daily_violations': 'Ежедневные нарушения',
    'grouped_by_date': 'Нарушения, сгруппированные по дате',
    'no_data_found': 'Данные не найдены',
    'violations_count': 'нарушение',
    'checks_count': 'чек',
    'location_clusters_next_version': 'Кластеры местоположений будут добавлены в следующей версии',
  },
  en: {
    // Main page
    'expeditor_tracker': 'Expeditor Tracker',
    'update_data': 'Update Data',
    'last_update': 'Last Update',
    'date_range': 'Date Range',
    'today': 'Today',
    'selected': 'Selected',
    'filter': 'Filter',
    'search_expeditors': 'Search expeditors...',
    'no_expeditors_found': 'No expeditors found',
    'try_changing_filter': 'Try changing the filter',
    'checks_count': 'Checks',
    'uzs': 'UZS',
    'filial': 'Branch',
    'phone': 'Phone',
    'transport': 'Transport',
    'status': 'Status',
    'project': 'Project',
    'warehouse': 'Warehouse',
    'city': 'City',
    'all_projects': 'All Projects',
    'all_warehouses': 'All Warehouses',
    'all_cities': 'All Cities',
    'all_statuses': 'All Statuses',
    'clear_all_filters': 'Clear All Filters',
    'active_filters': 'Active Filters',
    'daily_routes': 'Daily Routes',
    'statistics': 'Statistics',
    'total_checks': 'Total Checks',
    'total_amount': 'Total Amount',
    'unique_expeditors': 'Expeditors',
    'average_checks': 'Average Checks',
    'show_stats': 'Show Statistics',
    'hide_stats': 'Hide Statistics',
    'language': 'Language',
    'select_expeditor_to_view_checks': 'Select an expeditor to view checks',
    'loading_checks': 'Loading checks...',
    'no_checks_found': 'No checks found',
    'try_adjusting_filters': 'Try adjusting the date range or filters',
    'loading_expeditors': 'Loading expeditors...',
    'success_rate': 'Success Rate',
    'payment_methods': 'Payment Methods',
    'cash': 'Cash',
    'uzcard': 'UzCard',
    'humo': 'Humo',
    'click': 'Click',
    'enhanced_analytics_dashboard': 'Enhanced Analytics Dashboard',
    'main_dashboard': 'Main Dashboard',
    'telegram_contact_dev': 'Telegram (Contact Dev)',
    'analytics_violations': 'Analytics & Violations',
    'enhanced_analytics': 'Enhanced Analytics',
    'violation_analytics': 'Violation Analytics',
    'same_location_violations': 'Same Location Violations',
    'buzilishlar_nazorati': 'Violations Control',
    'tasks_management': 'Tasks Management',
    'yandex_tokens': 'Yandex Tokens',
    'check_pattern_analysis': 'Check pattern analysis - Time windows and geographic clusters',
    'logout': 'Logout',
    'real_time_analysis_fraud_detection': 'Real-time analysis and fraud detection',
    'comprehensive_statistics_insights': 'Comprehensive statistics and insights for expeditor performance',
    'export_all': 'Export All',
    'refresh': 'Refresh',
    'advanced_filters': 'Advanced Filters',
    'active': 'active',
    'visible': 'visible',
    'delivered': 'Delivered',
    'failed': 'Failed',
    'pending': 'Pending',
    'all_expeditor_checks': 'All expeditor checks',
    'successfully_delivered': 'Successfully delivered',
    'failed_deliveries': 'Failed deliveries',
    'awaiting_delivery': 'Awaiting delivery',
    'total_check_value': 'Total check value',
    'average_check': 'Average Check',
    'per_check_average': 'Per check average',
    'delivery_success_rate': 'Delivery success rate',
    'todays_checks': 'Today\'s Checks',
    'top_expeditors': 'Top Expeditors',
    'top_projects': 'Top Projects',
    'top_cities': 'Top Cities',
    'total_sum_uzs': 'Total Sum (UZS)',
    'average_check_sum_uzs': 'Average Check Sum (UZS)',
    'success_rate_percent': 'Success Rate (%)',
    'export': 'Export',
    'daily_check_distribution': 'Daily Check Distribution',
    'top_expeditors_by_check_count': 'Top Expeditors by Check Count',
    'top_projects_by_check_count': 'Top Projects by Check Count',
    'top_cities_by_check_count': 'Top Cities by Check Count',
    'chart_visibility_settings': 'Chart Visibility Settings',
    'dailyStats': 'Daily Stats',
    'hourlyStats': 'Hourly Stats',
    'topExpeditors': 'Top Expeditors',
    'topProjects': 'Top Projects',
    'topCities': 'Top Cities',
    'paymentMethods': 'Payment Methods',
    'loading_enhanced_statistics_page': 'Loading enhanced statistics page...',
    'filters': 'Filters',
    'date_from': 'Date From',
    'date_to': 'Date To',
    'expeditor': 'Expeditor',
    'min_checks': 'Min Checks',
    'max_checks': 'Max Checks',
    'radius_meters': 'Radius (meters)',
    'select_radius': 'Select radius',
    'window_duration_min': 'Window Duration (min)',
    'select_duration': 'Select duration',
    'clear_filters': 'Clear Filters',
    'analytics_summary': 'Analytics Summary',
    'time_window': 'Time Window',
    'most_active': 'Most Active',
    'total_records': 'Total Records',
    'avg_checks_window': 'Avg Checks/Window',
    'analytics_data': 'Analytics Data',
    'per_page': 'Per page',
    'showing': 'Showing',
    'to': 'to',
    'of': 'of',
    'records': 'records',
    'view_details': 'View Details',
    'violation_details': 'Violation Details',
    'check_details': 'Check Details',
    'location': 'Location',
    'most_active_expeditor': 'Most Active Expeditor',
    'area': 'Area',
    'actions': 'Actions',
    'date_time': 'Date & Time',
    'previous': 'Previous',
    'next': 'Next',
    'page': 'Page',
    'success': 'Success',
    'error': 'Error',
    'data_refreshed_successfully': 'Data refreshed successfully',
    'failed_to_load_analytics_data': 'Failed to load analytics data',
    'report_exported_successfully': 'Report exported successfully',
    'failed_to_load_violation_checks': 'Failed to load violation checks',
    'loading_analytics_dashboard': 'Loading analytics dashboard...',
    'no_analytics_data_available': 'No analytics data available',
    'retry': 'Retry',
    'violation_analytics': 'Violation Analytics',
    'real_time_pattern_detection_analysis': 'Real-time pattern detection and analysis',
    'apply_filters': 'Apply Filters',
    'clear_all': 'Clear All',
    'total_violations': 'Total Violations',
    'checks_involved': 'Checks Involved',
    'expeditors_count': 'Expeditors',
    'avg_radius': 'Avg Radius',
    'top_violators': 'Top Violators',
    'violators': 'Violators',
    'violation_checks': 'Violation Checks',
    'geography': 'Geography',
    'map': 'Map',
    'time': 'Time',
    'severity': 'Severity',
    'level': 'Level',
    'trends': 'Trends',
    'trend': 'Trend',
    'min_radius': 'Min Radius (m)',
    'max_radius': 'Max Radius (m)',
    'violation_checks_data': 'Violation Checks Data',
    'click_to_load_violation_checks': 'Click to load violation checks',
    'client': 'Client',
    'total_sum': 'Total Sum',
    'top_10_violators': 'Top 10 Violators',
    'most_frequent_violation_patterns': 'Most frequent violation patterns',
    'avg': 'Avg',
    'violations_count': 'violations',
    'click_for_details': 'Click for details',
    'performance_metrics': 'Performance Metrics',
    'detailed_expeditor_statistics': 'Detailed expeditor statistics',
    'avg_v': 'Avg/V',
    'geographic_hotspots': 'Geographic Hotspots',
    'areas_with_highest_violation_density': 'Areas with highest violation density',
    'time_analysis': 'Time Analysis',
    'violation_patterns_by_time_periods': 'Violation patterns by time periods',
    'daily_distribution': 'Daily Distribution',
    'violations_by_day_of_week': 'Violations by day of week',
    'hourly_pattern': 'Hourly Pattern',
    'peak_violation_hours': 'Peak violation hours',
    'severity_levels': 'Severity Levels',
    'categorized_by_violation_radius': 'Categorized by violation radius',
    'critical': 'Critical',
    'warning': 'Warning',
    'minor': 'Minor',
    'meters': 'meters',
    'daily_trend_analysis': 'Daily Trend Analysis',
    'violation_trends_over_time': 'Violation trends over time',
    'filters': 'Filters',
    'refresh': 'Refresh',
    'updated': 'Updated',
    'data_updated': 'Data updated',
    'failed_to_load_data': 'Failed to load data',
    'from_date': 'From Date',
    'to_date': 'To Date',
    'expeditor': 'Expeditor',
    'all': 'All',
    'min_checks': 'Min Checks',
    'search': 'Search',
    'total_violations': 'Total Violations',
    'suspicious_patterns': 'Suspicious Patterns',
    'unique_expeditors': 'Expeditors',
    'total_checks': 'Total Checks',
    'top_violators_by_risk': 'Top Violators by Risk (TOP 10)',
    'sorted_by_risk_level': 'Sorted by risk level',
    'unknown': 'Unknown',
    'checks': 'checks',
    'violations': 'violations',
    'suspicious': 'suspicious',
    'critical': 'critical',
    'view': 'View',
    'daily_violations': 'Daily Violations',
    'grouped_by_date': 'Violations grouped by date',
    'no_data_found': 'No data found',
    'violations_count': 'violations',
    'checks_count': 'checks',
    'location_clusters_next_version': 'Location clusters will be added in the next version',
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('uz')

  // Load saved language from localStorage
  useEffect(() => {
    if (typeof window === 'undefined') return
    try {
      const savedLanguage = localStorage.getItem('user_language') as Language
      if (savedLanguage && ['uz', 'ru', 'en'].includes(savedLanguage)) {
        setLanguage(savedLanguage)
      }
    } catch (error) {
      console.error('Error loading saved language:', error)
    }
  }, [])

  // Save language to localStorage
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    if (typeof window !== 'undefined') {
      try {
        localStorage.setItem('user_language', lang)
      } catch (error) {
        console.error('Error saving language:', error)
      }
    }
  }

  // Translation function
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
